### ISSUE TITLE
Re-connect feature

### ISSUE THREAD

**Issue by identisoft-alaric** [aws/aws-iot-device-sdk-embedded-C#101]
We have just ported your library to our  LPC1830 (Cortex-M3 180MHz) device using BearSSL, and everything is working like a dream. Thanks very much (developers).

Just one question about the "reconnect" logic, is there a reason why it stops trying to reconnect after the "AWS_IOT_MQTT_MAX_RECONNECT_WAIT_INTERVAL" 128000  (128 seconds). On our device we have changed your library to never stop trying to reconnect and increased the "AWS_IOT_MQTT_MAX_RECONNECT_WAIT_INTERVAL" to 1hr.

If the device reaches its max backoff time then the only way to get it to try and reconnect is to reset or power up the device again which is not an option for us because the device is normally installed at a site where it will be maintained via AWS (cloud software). A #define option for this may be a nice feature.

Thanks,
Alaric

**Comment by chaurah** [comment]
Hi @identisoft-alaric,
Glad to hear your porting effort was succesful. We provide an API "aws_iot_mqtt_attempt_reconnect" for this use case. If the library stops connecting because the max wait interval has been reached, your code can just call this API. I do however think it may be a good idea to have the algorithm keep attempting reconnect with the maximum value, once it has been reached. I will look into adding an API/#define that allows this functionality.

Please do let us know if you have further suggestions. Thank you for using AWS IoT.

Rahul

**Comment by identisoft-alaric** [comment]
Thanks Rahul for your reply.

**Comment by chaurah** [comment]
Hi @identisoft-alaric,
      I am closing this issue as we haven't heard anything new from you for several days now. If you have any further questions, please feel free to open a new issue. Thank you for using AWS IoT.

Rahul
