### ISSUE TITLE
Buffer overflow in parseStringValue()

### ISSUE THREAD

**Issue by bboccoqq** [aws/aws-iot-device-sdk-embedded-C#119]
https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/51ff90b9c29e27fcbe93c968d04008949e764d5f/src/aws_iot_json_utils.c#L194

The memcpy() is limiting the size of the copy based on the size of the source data, not the destination buffer. There is no buffer size passed to this function.

I think there is a fundamental issue when the source string comes from the thing shadow being updated from the cloud, since the buffer associated with the thing shadow key does not pass a size in the jsonStruct_t object. That can be worked around by having the string buffers sizes set to SHADOW_MAX_SIZE_OF_RX_BUFFER, but that seems like overkill.

**Comment by hedeshianaws** [comment]
Thank you for reporting this issue. You are absolutely correct that this can overflow the buffer.  I did some digging in the code and I believe the correct course of action would be to modify `struct jsonStruct` with a size for pData (such as below). This would require users to change their code but would be the safest and most correct option.  Further, this size check should be enforced by all parseXxxValue() functions called by UpdateValueIfNoObject(), not just parseStringValue(). For example, parseDoubleValue() assumes that pData is large enough to hold a double. This could easily be incorrectly  allocated by a user.

```c
struct jsonStruct {
	const char *pKey; ///< JSON key
	void *pData; ///< pointer to the data (JSON value)
	size_t pDataLen; ///< New parameter for the size of the buffer
	JsonPrimitiveType type; ///< type of JSON
	jsonStructCallback_t cb; ///< callback to be executed on receiving the Key value pair
};
```


In the example shadow_console_echo.c, pData is set to a character array of size SHADOW_MAX_SIZE_OF_RX_BUFFER.
```c
char stringToEchoDelta[SHADOW_MAX_SIZE_OF_RX_BUFFER];
...
int main(int argc, char** argv)
{
...
    deltaObject.pData = stringToEchoDelta;
...
}
```
Technically this works, but it is sweeping the problem under the rug hoping no one will notice. It is a poor solution for embedded users who are memory constrained. Setting everything to max size is simply not an option.


Since the fix will break existing users, I'll need to discuss internally on how to roll out this fix. I'll keep the issue open until there is a resolution.

**Comment by bboccoqq** [comment]
Alright, thanks for confirming this.
