### ISSUE TITLE
The repo licence should be set to MIT, not Apache2.0

### ISSUE THREAD

**Issue by danielsn** [aws/aws-iot-device-sdk-embedded-C#1195]
![Screen Shot 2020-09-03 at 9 06 41 PM](https://user-images.githubusercontent.com/4389518/92188033-655ec180-ee29-11ea-8ee2-bb41c674842b.png)

https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/development/LICENSE

_Originally posted by @danielsn in https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1162#discussion_r483330907_

**Comment by muneebahmed10** [comment]
The `master` branch contains v3 of the CSDK and is licensed under Apache 2.0. It's likely that is what GitHub shows as the license since it's the default branch. The `development` branch already has an [MIT License](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/development/LICENSE) file, but that won't be reflected on the GitHub sidebar until it becomes the new `master`.  I'll leave this issue open for now and we can close it when the branches are updated

**Comment by muneebahmed10** [comment]
The `development` branch has been moved to `master`.
