### ISSUE TITLE
v4_beta moving to v4_beta_deprecated

### ISSUE THREAD

**Issue by drewwestrick** [aws/aws-iot-device-sdk-embedded-C#1251]
Can anyone provide some detail into the deprecation of the v4_beta branch? I know this was never guaranteed to move forward, but it seems like there was an awful lot of work done on this front to just abandon it. We've started to do some development around it assuming that this was going to be a viable path in the future. Nothing too major, but again was expecting a little more information than is provided on the README page right now.

**Comment by abhidixi11** [comment]
Hello @drewwestrick 
Thanks for reaching out and apologies for any inconvenience that may have cause you due to the deprecation of the branch.  
Since we are releasing soon, we are in process of updating our readme files to add more information. Thanks for pointing it out.
We have  decided to focus on constrained micro controller based systems, therefore we refactored our code to meet the needs of such systems. The code is now available in master branch. 
v4_beta code will continue to exist. We will not add any new features, but we will fix critical bugs  and incorporate security patches. 
If you have any further questions please feel free to reach out.
Thanks.

**Comment by sarenameas** [comment]
Hello @drewwestrick ,

We elaborated on the README.md: https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1254
Do you have any other questions?

**Comment by sarenameas** [comment]
Hello @drewwestrick ,

I will close this issue for now. Please free to reopen or create a new issue if you have other concerns. 

Thank you,
Sarena
