### ISSUE TITLE
_aws_iot_mqtt_internal_yield timeout question

### ISSUE THREAD

**Issue by LDuAlle** [aws/aws-iot-device-sdk-embedded-C#1299]
_aws_iot_mqtt_internal_yield timeout is commented as the **max timeout** before the function return, but it's actually the **absolute timeout** the function will block for execution as doesn't seem like the while loop will break out until timeout. Is that expected behavior? If we break out the function when yieldRc == SUCCESS, will there be any problems? _aws_iot_mqtt_internal_yield should be called faster than incoming message rate, so as long as we got a message and everything is good, doesn't seem like it's necessary to keep staying in the while loop blocking other thread.

**Comment by abhidixi11** [comment]
Hello @LDuAlle ,
Thanks for reaching out. It is commented as  'max timeout '  because loop may exit earlier,  if a failure is encountered.  The the purpose of the loop is to dedicate fixed time for receiving messages in single threaded applications.  It is also designed to exit when there is failure. 

Since actual timeout is checked at the end, you can pass a small value or zero for timeout and the function will run exactly once.  In that case, you have to just make your application calls the yield function  faster than the incoming messages. That will avoid blocking the application.  Also you make sure you call the function  before keep-alive interval  is over to avoid getting disconnected from the broker. 

Please let me know if you have any further questions.

**Comment by abhidixi11** [comment]
Hello @LDuAlle 
I'm closing this issue. If you have any further questions, please feel free to open another issue.
Thanks.
