### ISSUE TITLE
AWS C-SDK OTA on Mbed OS?

### ISSUE THREAD

**Issue by ccli8** [aws/aws-iot-device-sdk-embedded-C#1320]
Hi, 

This may be duplicate of #331 and we would like to get updated information on AWS OTA. Per survey, currently only AWS FreeRTOS supports OTA but C-SDK hasn't yet. In our case, we would like to run C-SDK on Mbed OS for its supporting miscellaneous networking channels. We have the following questions:

1. Do you have a plan to support OTA in C-SDK?
1. To enable AWS OTA on Mbed OS, what's the suggested approach?

**Comment by tgsong** [comment]
Hi,

Thanks for reaching out.

1. Yes, actually we're working on it right now. We are expecting OTA to be released as part of C-SDK before the end of this year.
2. Although I'm not familiar with Mbed OS, since C-SDK is OS agnostic, it should be able to run on that too. You can check the latest release, https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/202009.00. As to OTA, after it's ready in C-SDK, we will be releasing a new porting document at the same time for user who needs to port it to a different OS other than FreeRTOS and Linux. Basically the new OTA library is designed to be able to run on any OS, you just need to implement some interface using Mbed OS API.

**Comment by cyliangtw** [comment]
Hi  @tgsong ,
      Appreciate your OTA plan. Some of our customers applied AmazonFreeRTOS OTA-Agent 1 year ago and now is blocking in the compatibility issue of server side in the migration into Linux platform.
Will this OTA cover the features of AmazonFreeRTOS OTA-Agent ?
      https://docs.aws.amazon.com/freertos/latest/userguide/ota-agent-library.html

**Comment by tgsong** [comment]
I suppose you mean "client side"? Our OTA service doesn't limit which platform the client is running. The new OTA library in C-SDK will support Linux platform by default, you don't need to do any porting work and we will provide a demo in this repository.

**Comment by cyliangtw** [comment]
Hi @tgsong ,
Yes, I mean client side. The customer current system is client side running "AmazonFreeRTOS OTA-Agent" and utilize "Create a FreeRTOS OTA update job" in server side.
They want to keep current AWS-IoT server code/setting and only migrate device/client side. According to your C-SDK OTA, could it accept the job document of "FreeRTOS OTA update job"  ?

![image](https://user-images.githubusercontent.com/14323432/96071703-426a0780-0ed5-11eb-9f28-2d16859b7577.png)

**Comment by tgsong** [comment]
Yes, it will be backward compatible, the name **Create a FreeRTOS OTA update job** might be confusing after we add OTA to c-sdk since it will not be limited to FreeRTOS anymore. I'll share this feedback to our team, thanks!

**Comment by cyliangtw** [comment]
Hi @tgsong,
    Thanks a lot. This OTA with backward compatibility of FreeRTOS OTA job is very much useful for existing AFR customers.

**Comment by ravibhagavandas** [comment]
@cyliangtw 

I  am closing this issue. Please feel free to reopen if you have further questions or feedback.
