### ISSUE TITLE
How does the install for the recent release 202009.00 work? 

### ISSUE THREAD

**Issue by Kristallfee** [aws/aws-iot-device-sdk-embedded-C#1344]
Hello!

I try to include the aws iot emb c sdk into my project, and I saw a cmake-install.cmake file. Installing would make it easier to include. What do I need to configure and to call to install it? 

Thank you 

Simone

**Comment by aggarw13** [comment]
Hi @Kristallfee, we do not support a **cmake-install.cmake** file or an installation target in the most recent release version [202009.00](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/202009.00). 

To understand your use-case, can you explain what functionality you are looking from an installation target? 
Are you looking for the header files to be installed in a system path (like `/usr/local/include` on Linux platforms) so that you can include them in your project? 
Also, are you looking for the libraries to be installed (as **.a**/static archives or **.so**/dynamic libraries) in the system (at `/usr/local/lib` on Linux platform)?

The CMake build configuration of the 202009.00 release does provide a way to build the **coreMQTT**, **Device Shadow** and **coreJSON** submodules as CMake libraries. Instead, we build the library files directly along with the demo source files (present under the `demos/` folder) in the demo project build configuration. 
For example, the [Device Shadow demo project](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/202009.00/demos/shadow/shadow_demo_main/CMakeLists.txt#L23-L28) CMake configuration builds all the source files of the Device Shadow, coreMQTT and coreJSON libraries along with the demo source file. 

If you are using the 202009.00 release, you would not be able to build the submodules as libraries and install them from the present build configuration. If you are looking to build and install the libraries as static archives or dynamic libraries in your project, you can refer to `test/CMakeLists.txt` file of the submodule repositories for reference on CMake library build configuration. (For example, coreMQTT repository builds the MQTT library as a CMake library target [here](https://github.com/FreeRTOS/coreMQTT/blob/a867f4cf4819f3bc9a950e0f611e1db5f8ec7c42/test/CMakeLists.txt#L34-L49))

**Comment by Kristallfee** [comment]
Hello @aggarw13, 

thank you for your answer! Yes, I was searching for a way to install the header files in a system path or a own defined path and for the libs to be installed. 

Thank you for your links, I will try to build them with the demos on my own.

Thank you, 
Simone

**Comment by yourslab** [comment]
Hi @Kristallfee

The C SDK now supports installation.

Documentation can be found in the [README](https://github.com/aws/aws-iot-device-sdk-embedded-C#installation).
