### ISSUE TITLE
AWS IoT Core Now Supports MQTT Connections with Certificate Based Client Authentication On Port 443

### ISSUE THREAD

**Issue by fedex03** [aws/aws-iot-device-sdk-embedded-C#140]
Hi there,
I read the article: [https://aws.amazon.com/about-aws/whats-new/2018/02/aws-iot-core-now-supports-mqtt-connections-with-certificate-based-client-authentication-on-port-443/](url) that explains the possibility to use the port 443 for the MQTT connection.

I developed a project that uses the AWS IoT SDK ( C language ) with the standard MQTT port 8883.

Does the AWS IoT SDK support this new feature? Is it possible to open the MQTT connection through the port 443?

Thanks in advance!
Federico

**Comment by dcgaws** [comment]
Federico, a 443 connection isn’t officially supported by the C SDK. 

However, it’s straightforward to modify that code to take advantage of the AWS IoT ALPN feature support for MQTT over port 443. For reference, take a look at the equivalent implementation in Amazon FreeRTOS, including the call to mbedtls_ssl_conf_alpn_protocols at https://github.com/aws/amazon-freertos/blob/master/lib/tls/aws_tls.c#L492. 

Based on that, a similar approach for the embedded C SDK would be to add the call to mbedtls_ssl_conf_alpn_protocols immediately before the existing call to mbedtls_ssl_setup in network_mbedtls_wrapper.c!iot_tls_connect. At the top of the latter function, add a local variable for the ALPN protocol string:

`const char *alpnProtocols[] = { "x-amzn-mqtt-ca", NULL };`

Pass that as the second parameter in your call to mbedtls_ssl_conf_alpn_protocols. Finally, don’t forget to connect your socket to port 443 (i.e., rather than 8883).

**Comment by gordonwang0** [comment]
#141

**Comment by fedex03** [comment]
@dcgaws thanks for your very useful reply! 
Unfortunately, in my project I used the TLS socket provided by my MCU (CC3200) in hardware and I removed the mbedTLS.

I'll try to understand if the CC3200 supports thee ALPN TLS extension. If not, I'll switch to mbed again.

Thanks for your time.
Federico

**Comment by gordonwang0** [comment]
Closing issue as resolved.  Please reopen if you have any further questions.
