### ISSUE TITLE
Should include <sys/time.h> for struct timeval in sockets_posix.c

### ISSUE THREAD

**Issue by xiongyu0523** [aws/aws-iot-device-sdk-embedded-C#1411]
Otherwise struct timeval will be undefined.

**Comment by aggarg** [comment]
I dumped the pre-processor output for `sockets_posix.c` on Ubuntu and I see that the following definition of `struct timeval` is pulled because of `#include <netdb.h>`:

```c
struct timeval
{
  __time_t tv_sec;
  __suseconds_t tv_usec;
};
```
Though, I do agree with you that for compliance, we should add `#include <sys/time.h>`. The following PR adds it: https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1413

Thank you for bringing it to our attention.

**Comment by xiongyu0523** [comment]
Thanks for confirm. On my platform, (Linux 5.4.59 + musl libc 1.2) there is no definition in <netdb.h> for this structure. So I guess <sys/time.h> is more compatible.
