### ISSUE TITLE
Apache 2.0 + EPLv1.0 compatible?

### ISSUE THREAD

**Issue by vulptex** [aws/aws-iot-device-sdk-embedded-C#142]
Hi,

i wonder if those licenses are incimpatible. Is it valid to base on EPL 1.0 with a own Apache 2.0 license?

Wikipedia says:
https://en.wikipedia.org/wiki/Eclipse_Public_License#Derivative_works

This sounds like, aws-iot lib CAN have both liceneses and there are no incompatibilities, right?

Can yomeone clarify this?

Thanks
 Andi

example:
aws_iot_mqtt_client.h

Apache:
/*
 * Copyright 2010-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

// Based on Eclipse Paho.
/*******************************************************************************
 * Copyright (c) 2014 IBM Corp.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v1.0 which accompany this distribution.
 *
 * The Eclipse Public License is available at
 *    http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 *   http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *    Ian Craggs - initial API and implementation and/or initial documentation
 *    Xiang Rong - 442039 Add makefile to Embedded C client
 *******************************************************************************/

**Comment by hyandell** [comment]
Hi Andreas,

I'm going to avoid talking about incompatibilities as that's a conversation for you to have with your legal advisor. Noting btw that I'm not a lawyer, just a member of the Open Source Program Office at Amazon.

Our source header means that the file contains some content that is under Apache 2.0, and some content that is under (EPL 1.0 and EDL 1.0). Note that the paho C about.html says:

'The Eclipse Foundation makes available all content in this plug-in ("Content"). Unless otherwise indicated below, the Content is provided to you under the terms and conditions of the Eclipse Public License Version 1.0 ("EPL") and Eclipse Distribution License Version 1.0 ("EDL").'

Eclipse explain that this is a choice of license here: https://eclipse.org/legal/eplfaq.php#DUALLIC

Note that the EDL is a license within the BSD family.

None of this covers whether you should consider Apache 2.0 and EDL 1.0, or Apache 2.0 and EPL 1.0, as compatible, but hopefully it provides with you some additional facts to help you make that decision.
