### ISSUE TITLE
ClientData.packetTimeoutMs is not used. (V3.X.X)

### ISSUE THREAD

**Issue by tenpa1105** [aws/aws-iot-device-sdk-embedded-C#1517]
pClient->clientData.packetTimeoutMs is referenced in _aws_iot_mqtt_internal_read_packet of aws_iot_mqtt_client_common_internal.c but it is not used.
```
	Timer packetTimer;
	init_timer(&packetTimer);
	countdown_ms(&packetTimer, `pClient->clientData.packetTimeoutMs);
```

I think that this parameter should be specified when waiting the rest of the buffer.
because if pTimer(argument of _aws_iot_mqtt_internal_read_packet) is short, timeout occur when waiting large size packet.
 ```
	/* 3. read the rest of the buffer using a callback to supply the rest of the data */
	if(rem_len > 0) {
                rc = _aws_iot_mqtt_internal_readWrapper( pClient, offset, rem_len, &packetTimer, &read_len );
		if(SUCCESS != rc || read_len != rem_len) {
			return FAILURE;
		}
	}
```

**Comment by muneebahmed10** [comment]
Hi @tenpa1105,

Thank you for bringing this to our attention. It does look like the last call to `_aws_iot_mqtt_internal_readWrapper` should be using `packetTimer`, and it seems to have been overlooked during some restructuring in #177. However, due to #1475, reads do not actually use the provided timer any more, and are instead controlled by `IOT_SSL_READ_RETRY_TIMEOUT_MS`. I created and merged PR #1518 to remove the unused timer and add a comment to the declaration of `packetTimeoutMs` to clarify that it is unused.

I will close this issue as the PR has been merged, but please let us know if you have any further questions. Thank you
