### ISSUE TITLE
[Bug]: Registering delta after aws_iot_shadow_update call with persistent flag set to false, times-out

### ISSUE THREAD

**Issue by anubhav1** [aws/aws-iot-device-sdk-embedded-C#1524]
This piece of code is failing with time out error:

```
rc = aws_iot_shadow_update(&mqttClient, AWS_IOT_MY_THING_NAME, JsonDocumentBuffer, ShadowUpdateStatusCallback, NULL, 4, false);
rc = aws_iot_shadow_register_delta(&mqttClient, &carDoor);
    if(SUCCESS != rc) {
        ESP_LOGE(TAG, "Shadow Register Delta Error");
    }
    
```
But this piece of code runs without problem:
```
rc = aws_iot_shadow_update(&mqttClient, AWS_IOT_MY_THING_NAME, JsonDocumentBuffer, ShadowUpdateStatusCallback, NULL, 4, true);
rc = aws_iot_shadow_register_delta(&mqttClient, &carDoor);
    if(SUCCESS != rc) {
        ESP_LOGE(TAG, "Shadow Register Delta Error");
    }    
```
Is it a bug?

**Comment by leegeth** [comment]
@anubhav1,

Thanks for bringing this issue to our attention and apologize for the delay in response. Can you please let us know which version of the SDK you are using?

**Comment by anubhav1** [comment]
v3.0.1

**Comment by leegeth** [comment]
@anubhav1, 

Thanks. We are looking into the issue.

**Comment by leegeth** [comment]
@anubhav1 ,

The aws_iot_shadow_update() API will internally subscribe to `/update/accepted` and `/update/deleted` MQTT topics. Then it publishes to MQTT topic `/update`. As a result of the publish, there will be an incoming publish to either `/update/accepted` or `/update/deleted` topics.  In order for the incoming publish to be read, a network read is required.

In the example code you provided, the aws_iot_shadow_register_delta() API will attempt to subscribe to `/update/delta`. As part of the subscription completion, it will try to read a SUBACK from network. Since this is the first attempt to read from network after a publish is sent to `/update` topic, there will be incoming publishes to either `/update/accepted` or `/update/deleted` MQTT topics. SUBACK may be received only after the incoming publish is processed. However in case of a persistent flag(true), the incoming publishes are processed and the SUBACK is received before the read attempt is timed out. In contrast, when a persistent flag is set to false, 2 additional operations to unsubscribe from `/update/accepted` and `/update/deleted` MQTT topics will be attempted before a SUBACK is attempted to be received. This may not be completing within the timeout.

In order to correctly handle the situation, if there is a network read attempt done to process the incoming publish and unsubscribe operations, the example code will work in both persistent case and non persistent case. Please refer to the [aws_iot_shadow_update() API documentation](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v3.0.1/include/aws_iot_shadow_interface.h#L186-L208) for more details.

So the correct sequence would be 
```
rc = aws_iot_shadow_update(&mqttClient, AWS_IOT_MY_THING_NAME, JsonDocumentBuffer, ShadowUpdateStatusCallback, NULL, 4, false);
if(SUCCESS != rc) {
        ESP_LOGE(TAG, "Shadow Update Error");
}
rc = aws_iot_shadow_yield(&mqttClient, 200);
if(SUCCESS != rc) {
        ESP_LOGE(TAG, "Shadow Yield Error");
}
rc = aws_iot_shadow_register_delta(&mqttClient, &carDoor);
if(SUCCESS != rc) {
        ESP_LOGE(TAG, "Shadow Register Delta Error");
}
```

Please let us know if you have any follow up questions.
