### ISSUE TITLE
v3.1.5 tag release CHANGELOG.md hasn't been updated

### ISSUE THREAD

**Issue by arabed** [aws/aws-iot-device-sdk-embedded-C#1535]
v3.1.5 tag release CHANGELOG.md hasn't been updated. 
It seems CHANGELOG.md hasn't been updated for a while. This make it hard to see if there is any value or particular issue solved worth to upgrade from an older version (3.0.1) to the most recent (3.1.5) one. Also it is not clear if there is a API change from 3.0.x to 3.1.x versions.

**Comment by yourslab** [comment]
You can take a look at the commit history to see what changes have been made. Each commit corresponds to a particular version. We are still considering whether the CHANGELOG.md needs to be updated because there are no API changes or features added after 3.0.1, only fixes.

**Comment by arabed** [comment]
Fair enough, just thought it is good place to see the version enumeration and information. 
Also are you guys considering to support OpenSSL as an option alternative to mbedtls for this embedded-C version?

**Comment by yourslab** [comment]
No, but the latest release (202012) supports OpenSSL. We highly recommend using this release if possible since the new libraries are refactored to a much higher standard (Buffer overflow checking, 100% branch coverage, and more).

Although if you really want to stick to the older version, you can take the code from here 
https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/platform/posix/transport/src/openssl_posix.c
and use it to come up with something equivalent to `network_mbedtls_wrapper.c` (i.e. make a `network_openssl_wrapper.c`).

**Comment by mingyue86010** [comment]
It looks customer question has been answered. Will Close this issue. If having any further questions, please feel free to open a new ticket. Thank you!
