### ISSUE TITLE
Query on aws example

### ISSUE THREAD

**Issue by hvishu** [aws/aws-iot-device-sdk-embedded-C#154]
I have been asked to raise this question here.  See this link
https://github.com/espressif/esp-idf/issues/1810#issuecomment-378592004

From the examples/aws_iot/thing_shadow/main/thing_shadow_sample.c

in aws_iot_task(), I see below line
while(NETWORK_ATTEMPTING_RECONNECT == rc || NETWORK_RECONNECTED == rc || SUCCESS == rc) {
...
...
}
Seems if the error returned is "NETWORK_ATTEMPTING_RECONNECT" or "NETWORK_RECONNECTED", attempt will be made to connect and be in while loop.

The list of errors in IoT_Error_t, is quite a few. Are there any of these errors possible? If so, what is the sequence to recover from tem?

**Comment by gordonwang0** [comment]
Hi @hvishu,

The [loop you referenced](https://github.com/espressif/esp-idf/blob/2935e958fc4b43c90550364d76ae8f0a3cb8488d/examples/protocols/aws_iot/thing_shadow/main/thing_shadow_sample.c#L289) is an example of how to repeatedly update a Thing Shadow.  The return values `NETWORK_ATTEMPTING_RECONNECT`, `NETWORK_RECONNECTED`, and `SUCCESS` are the successful values on which the loop continues.

Any other return value is an error.  You won't see every `IoT_Error_t` returned by functions in that loop.  You'll probably see `FAILURE` most commonly, although `JSON_PARSE_ERROR`, `SHADOW_JSON_BUFFER_TRUNCATED`, and `JSON_PARSE_ERROR` are also common.  Other error values may be seen too, but the ones I listed are the most common for Shadow updates.

In general, recovering from an error in that loop requires changes to other parts of the code, which is why it isn't done in that example.  The details of how to recover from every error value is beyond the scope of a single post (there are too many scenarios to list).  But if you are encountering any specific error values, please comment below and I can give more details on it.

**Comment by hvishu** [comment]
Hi @gordonwang0 
Thanks for the reply.
Since we are launching a product using this h/w and s/w, I would like to understand all possible errors and how to recover from each of them.
I was under the impression that though not mentioned in the test application, there would be test cases /documentation for the all possible errors and recovery sequence from it, hence the question.

I don't have specific question as of now, I would still like to understand all possible errors that could be returned by the aws_iot_task() in the example, namely
aws_iot_shadow_yield()
aws_iot_shadow_init_json_document()
aws_iot_shadow_add_reported()
aws_iot_finalize_json_document()
aws_iot_shadow_update()

Once I have the answer, we will simulate each of these errors in our product and see if the recovery sequence can work.

Regards
Vishwa

**Comment by gordonwang0** [comment]
Hi @hvishu,

All of the functions mentioned can return `NULL_VALUE_ERROR`.  This means that something is wrong with an argument.

The JSON functions `aws_iot_shadow_init_json_document`, `aws_iot_shadow_add_reported`, and `aws_iot_finalize_json_document` return `SHADOW_JSON_ERROR` on error.  `aws_iot_shadow_init_json_document` may also return `SHADOW_JSON_BUFFER_TRUNCATED`.  In general, both of these return values mean that the argument `pJsonDocument` (a buffer to put the JSON document in) was too small in some way.

`aws_iot_shadow_update` can return `MQTT_CONNECTION_ERROR` (`pClient` not connected) or `FAILURE` if a Shadow update is rejected.  It may also return any of the error codes returned by the underlying MQTT client, such as `NETWORK_DISCONNECTED_ERROR` or `MQTT_CLIENT_NOT_IDLE_ERROR`.

`aws_iot_shadow_yield` is the most complex of these functions.  It may return many error codes, such as `NETWORK_MANUALLY_DISCONNECTED`, `NETWORK_DISCONNECTED_ERROR`, `MQTT_CLIENT_NOT_IDLE_ERROR`, and others.  Simulating each of the error codes returned by this function may not be good use of time.  Any error code returned by this function generally means the MQTT connection has dropped, i.e. network issues.  The SDK has auto-reconnect functionality that will attempt to reconnect should the MQTT connection drop.  If the `yield` function _still_ returns errors with the reconnect feature enabled, then there are likely network issues that the SDK can't recover from.

**Comment by hvishu** [comment]
Ok, Thanks.  Will check as per your description and let you know, if you have any other questions.

**Comment by gordonwang0** [comment]
You're welcome.  I'll close this issue now.
