### ISSUE TITLE
Event callback function not invoking in infinite loop

### ISSUE THREAD

**Issue by vijayrakesh13** [aws/aws-iot-device-sdk-embedded-C#1573]
Hi,

EventCallback( ) function is not invoking while running code in an infinite loop in shadow demo example application. I had modified application such a way that after subscribing to the delta topic I'm running application in infinite loop (while(1)) to receive delta update at anytime, but eventCallback( ) is not getting invoked. If I re-ran my application, before going into the infinite loop I receive a publish from delta.

**Comment by lundinc2** [comment]
Hi @vijayrakesh13,

I am investigating this issue and will get back to you with more details.

**Comment by aggarw13** [comment]
Hi @vijayrakesh13,
  
 For your application to receive an incoming MQTT from the `/update/delta` topic (and thereby, invoke the `eventCallback` callback), the state of the shadow document needs to change on your AWS account through publishing of the desired state (done [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/demos/shadow/shadow_demo_main/shadow_demo_main.c#L796-L822) in the Shadow demo), i.e. the _desired_ and _reported_ states of the Shadow should differ.
 
 Can you clarify that your application sends the publish message to update the desired state on the Shadow?
 
 Also, if you have put the entire logic of the demo code (after subscription to the delta topic) in an infinite loop, then the application would receive an incoming PUBLISH on the delta topic only in the first iteration because that is when the "desired" state of the Shadow differs (or has "_delta_") from the "reported" state of Shadow. After the demo sends the PUBLISH message ([here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/demos/shadow/shadow_demo_main/shadow_demo_main.c#L834-L853)) to update the Shadow's "reported" state to match the "desired" state, there is no "_delta_" between the _desired_ and _reported_ states anymore, and thus, the AWS IoT Device Shadow service will not send any messages on the `update/delta` topic anymore.
 
 Hope that helps.

**Comment by vijayrakesh13** [comment]
Hi @aggarw13,

Every time I ran my application I had made sure delta exists. I'm changing shadow variables from AWS console to create delta. Everything works fine when I run (subscribe `update/delta/ -> sleep(10) (creating delta from AWS console) -> `eventCallback` ), but not in infinite loop (subscribe `update/delta/ -> while(1) (creating delta from AWS console) -> no callback )

Code attached [Reference.txt](https://github.com/aws/aws-iot-device-sdk-embedded-C/files/6073742/Reference.txt).

**Comment by aggarw13** [comment]
Hi @vijayrakesh13,

 Thank you for sharing your application code structure and clarifying about the setup on the AWS console. 
  
  For the `eventCallback` to be invoked, the `MQTT_ProcessLoop` function of the coreMQTT library needs has to be called as the `MQTT_ProcessLoop` function performs the read operations on the network to receive incoming MQTT messages. 
 Within the Shadow demo, the `MQTT_ProcessLoop` function is called within the [SubscribeToTopic](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/demos/shadow/shadow_demo_main/shadow_demo_helpers.c#L800), [UnsubscribeFromTopic](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/demos/shadow/shadow_demo_main/shadow_demo_helpers.c#L863) and [PublishToTopic](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/demos/shadow/shadow_demo_main/shadow_demo_helpers.c#L940) functions. 
 Thus, within the non-infinite loop case in your application, you are reading the incoming PUBLISH message from AWS IoT Shadow service through the `shadow_operation(DELTA_UNSUB, NULL)` function that calls the `UnsubscribeFromTopic` function (which internally calls the `MQTT_ProcessLoop` function).
 
 If you would want the infinite-loop case of your application to receive messages from the network, you will have to add an explicit call to `MQTT_ProcessLoop` function.

**Comment by vijayrakesh13** [comment]
Hi @aggarw13,

Thank you!
