### ISSUE TITLE
How to add a custom include path in the CMAKE file?

### ISSUE THREAD

**Issue by mukesh-2538** [aws/aws-iot-device-sdk-embedded-C#1585]
I am cross-compiling for aarch64 platform using a different toolchain.
I have cross-compiled for openssl for the specific platform.

**I built the SDK using the command:**
```
cmake -S . -Bbuild -DCMAKE_TOOLCHAIN_FILE=/home/mukesh/trail/myown.cmake
```

**Contents of myown.cmake :**
```
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)


set(tools /home/mukesh/source/toolchain/linaro-aarch64-2018.08-gcc8.2)
set(CMAKE_C_COMPILER ${tools}/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${tools}/bin/aarch64-linux-gnu-g++)
set(OPENSSL_ROOT_DIR /home/mukesh/cross-openssl/compiled-openssl/lib/libcrypto.so)
```
**Cmake ran successfully and after this i ran the following inside build directory** :
```
make mqtt_demo_mutual_auth
```

**The error i am facing is**
```
:~/trail/aws-iot-device-sdk-embedded-C/build/demos/mqtt/mqtt_demo_mutual_auth$ make
[ 25%] Built target sockets_posix
[ 25%] Building C object platform/posix/transport/CMakeFiles/openssl_posix.dir/src/openssl_posix.c.o
In file included from /home/mukesh/trail/aws-iot-device-sdk-embedded-C/platform/posix/transport/src/openssl_posix.c:33:
/home/mukesh/trail/aws-iot-device-sdk-embedded-C/platform/posix/transport/include/openssl_posix.h:53:10: fatal error: openssl/ssl.h: No such file or directory
 #include <openssl/ssl.h>
```

It seems the toolchain does not have the required header files.
**Is there a way to include it using cmake?**

**Comment by dan4thewin** [comment]
OpenSSL is a dependency to build the TLS-using demos for Linux/POSIX type systems.  When building for FreeRTOS, mbedTLS is used instead, or perhaps WolfSSL.  If you only want to run something like the plaintext MQTT demo, then you don't need TLS.  Since you're cross compiling, I suspect you'll either need to build a TLS from source, or install dev packages for your target (or perhaps it's included with your toolchain).  There are several ways to change the arguments cmake gives to the compiler.  In particular, you can add to the lists given to `target_include_directories()` and `target_link_libraries()` in the `CMakeLists.txt` file for a given demo.

**Comment by vikivivi** [comment]
@mukesh-2538 For cross compilation, it is not so simple to just include openssl directory. 

The correct method is trying to get cmake to pass `--sysroot` flag to the GCC cross compiler. 
Logically, any project `CMakeLists.txt` does not required any changes if it is correctly written.

Most of the configuration should be done in  `CMAKE_TOOLCHAIN_FILE`. It should include many more parameters. You might want to check cmake documentation on these parameters.
* `CMAKE_SYSTEM_NAME`
* `CMAKE_SYSROOT`
* `CMAKE_LIBRARY_ARCHITECTURE`
* `CMAKE_SYSTEM_PROCESSOR`
* `CMAKE_C_COMPILER`
* `CMAKE_CXX_COMPILER`
* `CMAKE_FIND_ROOT_PATH`
* `CMAKE_FIND_ROOT_PATH_MODE_PROGRAM`
* `CMAKE_FIND_ROOT_PATH_MODE_LIBRARY`
* `CMAKE_FIND_ROOT_PATH_MODE_INCLUDE`
* `CMAKE_FIND_ROOT_PATH_MODE_PACKAGE`
