### ISSUE TITLE
Support for coreMQTT-Agent

### ISSUE THREAD

**Issue by n8o** [aws/aws-iot-device-sdk-embedded-C#1738]
Are there any plans to support coreMQTT-Agent in the SDK?

**Comment by yanjos-dev** [comment]
I'm unfamiliar with the repository that you shared, but I'd like to point you in the right direction.

The coreMQTT-Agent library requires a port for a MQTT protocol to work. The interfaces that are required can be found in the README.md file of the [coreMQTT-Agent repository](https://github.com/FreeRTOS/coreMQTT-Agent).

Here are some examples that show how to port the coreMQTT-Agent library to be used with the coreMQTT library.
1. [coreMQTT Agent Demo](https://github.com/FreeRTOS/coreMQTT-Agent-Demos).
2. [FreeRTOS/FreeRTOS demo](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS-Plus/Demo/coreMQTT_Windows_Simulator/MQTT_Multitask)
3. [aws/amazon-freertos Demo](https://github.com/aws/amazon-freertos/blob/edc6a02aeae0a0091b544fda4d82b07d24348ea9/demos/coreMQTT_Agent/mqtt_agent_task.c#L478-L521)

You can also find documentation for the coreMQTT-Agent library interfaces and for the library in general [here](https://freertos.org/Documentation/api-ref/coreMQTT-Agent/docs/doxygen/output/html/index.html).

I would recommend these as starting points to understand how to port the coreMQTT Agent library.

**Comment by ravibhagavandas** [comment]
Hi @n8o 

To add on to this, the freertos porting implementation of coreMQTT agent library can be found in the coreMQTT Agent Demo repository [here](https://github.com/FreeRTOS/coreMQTT-Agent-Demos/tree/main/lib/FreeRTOS/mqtt-agent-interface). Since you are using FreeRTOS along with the  ESP-IDF, the port could be directly integrated into your project. Once porting implementation, you can take a look at the [demo tasks](https://github.com/FreeRTOS/coreMQTT-Agent-Demos/tree/main/source/demo-tasks) to see how to use coreMQTT agent to run multiple MQTT tasks sharing same connection.

**Comment by abhidixi11** [comment]
Hello @n8o I'm closing this issue. If you have any further questions, please feel free to open another issue.
