### ISSUE TITLE
WIFI_STORAGE_FLASH usage

### ISSUE THREAD

**Issue by hvishu** [aws/aws-iot-device-sdk-embedded-C#178]
In our current app, with esp_wifi_set_storage(), we are using WIFI_STORAGE_RAM.  I would like to understand how to use WIFI_STORAGE_FLASH.
If WIFI_STORAGE_FLASH is used,
a. Where exactly in NVS configuration information stored?
b. Does this include wifi_config_t.sta.ssid and wifi_config_t.sta.password ?
c. How to check in app if the config information is already saved in NVS, so that it can be reused instead of reinitializing using esp_wifi_init()

**Comment by lt72** [comment]
Hi hvishu,
are you running against FreeRTOS or are you actually using the C-SDK on your own RTOS (or no -RTOS)?

**Comment by hvishu** [comment]
Hi,
I am using FreeRTOS, ESP_IDF release as 3.0

**Comment by lt72** [comment]
Thank you for letting us know. Since you are using FreeRTOS, you will be likely using the FreeRTOS libraries. Please let me know if my assumption is wrong.
This repo contains libraries that a developer can use when targeting any RTOS or OS other than FreeRTOS (e.g. embedded Linux, etc...).
Could you please open the issue on the FreeRTOS repo at https://github.com/aws/amazon-freertos/issues and close this issue instead?

**Comment by hvishu** [comment]
I dont think it is related to FreeRTOS.  I am asking how to use the "WIFI_STORAGE_RAM" option with esp_wifi_set_storage().  Please see my original question.  As per me this needs to be answered in this group or **espressif/esp-idf** gropu

**Comment by lt72** [comment]
This repo does not support ESP devices esplicitly. The FreeRTOS repo I indicated above does (ESP32 is one of many platforms that FreeRTOS for AWS supports).
Please re-open the issue on the FreeRTOS repo as indicated above.

**Comment by hvishu** [comment]
OK, I will raise it there.
