### ISSUE TITLE
Replace mbedTLS with OpenSSL in fleet provision demo

### ISSUE THREAD

**Issue by lcycoding** [aws/aws-iot-device-sdk-embedded-C#1797]
Dear AWS developers,

I was developing with fleet provision demo recently, and noticed that the connection library using mbedTLS.
Wondering if mbedTLS could be replaced by OpenSSL like the other demo?
If so, how do we adapt the cmake config or is there any recommendation steps that we could do?

Best,

**Comment by archigup** [comment]
In the fleet provisioning demo, [mqtt_operations.c](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/demos/fleet_provisioning/fleet_provisioning_with_csr/mqtt_operations.c) would have to be updated to use OpenSSL instead of mbedTLS. This can be done by following code in other demos using OpenSSL. If this is done, the demo will use OpenSSL for connecting.

However, it will still require mbedtls as well. The demo uses corePKCS11 for credential storage, and corePKCS11 requires mbedtls for crypto operations. Additionally [pkcs11_operatiosn.c](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/demos/fleet_provisioning/fleet_provisioning_with_csr/pkcs11_operations.c) in the demo uses mbedTLS for crypo operations as well.
