### ISSUE TITLE
Cross-compiling on a T31 Board

### ISSUE THREAD

**Issue by Zevolusion** [aws/aws-iot-device-sdk-embedded-C#1799]
I try to cross-compiling on a T31 Board. But it occured error, seems like rt library could not compile.
How can I fix this?
![image](https://user-images.githubusercontent.com/16457119/165009910-6d801003-6e45-41e5-a874-7679f83d66b3.png)

**Comment by paulbartell** [comment]
@Zevolusion : could you share a bit more info about what arguments you've passed into cmake?

librt is located using the cmake [find_library](https://cmake.org/cmake/help/latest/command/find_library.html) function. you'll need to make sure the librt .so object is available in your cross compilation environment.

libRT is only required for a few other demos (listed below). So It may not be necessary depending on your use case.
http_demo_s3_download_multithreaded
ota_demo_core_http
ota_demo_core_mqtt

**Comment by Zevolusion** [comment]
My complier is mips-gcc472-glibc216-32bit-r2.3.3.
And I try another branch which is v4_beta_deprecated, it occurs same error:
![image](https://user-images.githubusercontent.com/16457119/165248429-1bc2dcdd-34c5-412d-92a1-131f342633e3.png)

**Comment by paulbartell** [comment]
@Zevolusion : For cmake to be able to find the librt library, it needs to know where to look. You can approach this in a couple different ways:

* build and use a [cmake toolchain file](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html) with all of the relevant paths defined... Something like this:
```
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSROOT /path/to/rootfs)
set(CMAKE_STAGING_PREFIX /path/to/install/directory)
set(CMAKE_C_COMPILER /path/to/gcc)
set(CMAKE_CXX_COMPILER /path/to/g++)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```
and then pass -DCMAKE_TOOLCHAIN_FILE=/path/to/mips-toolchain.cmake

* define the LIB and INCLUDE environment variables so that cmake can locate librt. For your toolchain, it's likely something like this:
```
export LIB=/path/to/toolchain/mips-linux-gnu/libc/usr/lib
export INCLUDE=/path/to/toolchain/mips-linux-gnu/libc/usr/include
```

**Comment by Zevolusion** [comment]
It works, Thanks! @paulbartell
