### ISSUE TITLE
Segmentation fault after OtaJobEventSelfTestFailed within 20s

### ISSUE THREAD

**Issue by Nomidia** [aws/aws-iot-device-sdk-embedded-C#1814]
Steps to reproduce:
1. After downloading the firmware, the otaThread will exit.
2. Then restart the demo, it will in self test mode, and OtaSelfTestTimer will be created
3. Since the version number has not changed, OTA_Shutdown will be invoked
4. In shutdownHandler, otaAgent will be clear
5. After several seconds the OtaSelfTestTimer expires, otaAgent.pOtaInterface->pal.reset will cause segfaul

[segfault.log](https://github.com/aws/aws-iot-device-sdk-embedded-C/files/9249990/segfault.log)

I think it will be better if we can stop the timer.

**Comment by dachalco** [comment]
Hi @Nomidia

Thank you for the detailed back trace and logs. This issue is mainly applicable to the linux platform port we supply for the demos, as it does not implement `pal.reset`. On an actual MCU, this trace would should end at step 4, where after returning from user's the MCU is[reset](https://github.com/aws/ota-for-aws-iot-embedded-sdk/blob/main/source/ota.c#L2170).

However, I think you've still pointed out a valid race condition as it's theoretically possible the selftest timer expires before reset is called, if the test duration were unreasonably tiny enough. I think you're right, the self-test timer should be [here](https://github.com/aws/ota-for-aws-iot-embedded-sdk/blob/main/source/ota.c#L2167).

**Comment by ActoryOu** [comment]
I believe this has been fixed by [commit in OTA repo](https://github.com/aws/ota-for-aws-iot-embedded-sdk/commit/01915aca936a45d92ea05db187a84e3e773b2d11). It has been patched into this repo, too. So, I'm going to close this issue.

Thanks a lot!
