### ISSUE TITLE
looking for a bare-metal example 

### ISSUE THREAD

**Issue by ahsf** [aws/aws-iot-device-sdk-embedded-C#1862]
I'm looking for a working example project for any microcontroller-devkit (ideally Cortex-M) running bare-metal without RTOS.

**Comment by kstribrnAmzn** [comment]
Hello @ahsf. Is this example you're looking for consuming the [aws-iot-device-sdk-embedded-C](https://github.com/aws/aws-iot-device-sdk-embedded-C) library in any way?

I assume you'll have a better time finding a baremetal project on the ARM forums. There are some related [posts](https://community.arm.com/support-forums/f/architectures-and-processors-forum/48832/a-simple-bare-metal-gicv3-in-aarch64)

**Comment by kstribrnAmzn** [comment]
A couple other questions as I'm curious - why do you want to go directly to metal? Typically an RTOS will give you both a simpler API set and more flexibility as you add more functionality. I'm a little biased since I work on the [FreeRTOS team](https://freertos.org/) but with good reason. FreeRTOS has been used in industry for decades and has a very passionate community who wants to help developers like yourself on [our forums](https://forums.freertos.org/).

**Comment by kstribrnAmzn** [comment]
Going to close out this issue since there haven't been any further questions AND this is more board/architecture specific. Feel free to reopen as needed.
