### ISSUE TITLE
Should I use self-defined MQTT topics or device shadow to interact with device?

### ISSUE THREAD

**Issue by xiongyu0523** [aws/aws-iot-device-sdk-embedded-C#199]
I have a gateway that many non-IP devices connected to, and the gateway does the protocol translation and represent itself as a single thing in AWS IoT Core. 

To manage device connected and control & report status of the leaf node, I see two possible way. 
1. Use device shadow, and put everything in the shadow json document. 
2. Use self-defined topics, so that application and gateway can use pub/sub to communicate at topic level.

What are the major differences, pros, and cons between these two approaches? Thanks

**Comment by ravibhagavandas** [comment]
If I understand correctly, option 1 is like a transparent/aggregating gateway where the device exchange a shadow json document to gateway and gateway forwards the document to MQTT broker in cloud. Whereas In Option 2  gateway will act as an MQTT broker and does publish and subscribe separately with the cloud and the device.
Option 1 is more simpler to implement and it will satisfy your use case as long as gateway is always connected to cloud. Also since gateway represents as a single thing in the cloud, you can multiplex many device connections onto a single connection to MQTT broker.
I think option 2 is more complex to implement as it needs gateway  to behave like a broker, which needs some session management and queuing. Its useful in cases where gateway is not connected to internet but still behaves like a broker to the device.

Hope this helps.

**Comment by xiongyu0523** [comment]
Thanks for the answer, I think you might misunderstand my question. I need to clarify:

1. The non-IP device talks to the gateway using Zigbee protocol or BLE protocol, in a raw payload. Then the gateway filter & send data to the cloud. There is a 'protocol translator' in the gateway to do this. 

2. The gateway runs an MQTT client only, to connect to AWS IoT Core.

**Comment by ravibhagavandas** [comment]
Its hard to weigh in on a good approach unless we know the details of the system and the requirements.
Could you elaborate more on the two approaches and what exact use cases they are trying to solve ?

**Comment by xiongyu0523** [comment]
OK. I'm designing a Zigbee Gateway. This Gateway act as Zigbee coordinator and can communicate to the whole Zigbee mesh network and also to the AWS IoT Core, so that Application can control device in Zigbee network and receive sensor data from the Zigbee network. 

Since all Zigbee devices do not have IP stack, the only thing present to AWS IoT Core is the gateway. So gateway need translate the Zigbee message to MQTT message. 

When a new Zigbee joins a network, the gateway will send this message to AWS IoT Core so that Apps can get notified and UI will be changed. In this specific use case, should I use the shadow service or raw MQTT with self-defined topics?

If shadow service is used. I will add an attribute "connected device: ["new device"]" in the shadow JSON and publish to $aws/things/myLightbulb/shadow/update. The application can subscribe the delta topic of shadow service to get the new update. 

If self-defined MQTT topic is used. I need to design an topics architect like /gw/mydevice/connected, and device publishes and application subscribe. 

I want to know the differences between this two approaches

**Comment by ravibhagavandas** [comment]
Its recommended to register each device as a separate thing in the cloud. That way you can have separate shadows for each devices and  fine grained policies for each shadows. This could be done for Non-IP devices as well because it needs to only have a valid certificate with the right policies attached.

**Comment by xiongyu0523** [comment]
Hi, Ravi

Thanks for your answers. 

Non-IP Zigbee node is extremely resources constrained and will only use common Zigbee language to communicate to the Gateway. Sometimes, it comes from a 3rd party. So I think it is not possible for those nodes to have a certificate?

So:

Option 1:

Gateway is the single registered thing, and communicate with the application through device shadow service. 

Option 2:
Gateway is the single registered thing, and communicate with the application through multiple MQTT topics:

From Gateway to Apps

gw/<IEEE addresss>/online
gw/<IEEE addresss>/devicejoined
gw/<IEEE addresss>/deviceleaved

...

From Apps to Gateway

gw/<IEEE addresss>/commands
gw/<IEEE addresss>/history

**Comment by ravibhagavandas** [comment]
Hi @xiongyu0523 ,

`Option 1` is more preferred option here as 

- It lets you easily manage all devices using a single shadow document. 
- Shadow provides flexibility of adding more properties to a device state (for example: colors for a light bulb) within the JSON document. Whereas you might need to create a new topic in `Option 2`.
- Gateway and app code will be lot more simpler as you can use existing iot shadow sdks.
- You can [trim ](https://docs.aws.amazon.com/iot/latest/developerguide/using-device-shadows.html#device-shadow-trim-messages)specific parts of shadow document and listen on those fields by republishing to a separate topic.

**Comment by AmirKeshavarz** [comment]
Hi Xiongyu and everybody,
This is a very late answer but may help some readers..

Based on your mentioned scenarios as I know ,shadows would be perfect if last state of device is needed. For example when a device resets it can ask its last state from AWS, or when a front UI wants to know last state of a device it can be rapidly retrieved from AWS again.

Also in some scenarios device needs time to adjust its attributes with desired values. In this scenario also device-shadow is a best practice as it presents both desired and reported with their update times.
