### ISSUE TITLE
Advice on using AWS IoT Thing shadow

### ISSUE THREAD

**Issue by umanayana** [aws/aws-iot-device-sdk-embedded-C#201]
Hello, 

I am working on a commercial product which provides IoT capabilities to lights. Lets call these lights channels. This is done via a gateway which talk a existing product. Currently our existing gateway already keep a internal database of the state of all the channels for existing data adaptors. A data adaptor is any protocol specific converter. For example our device support BACnet, HomeKit etc. We now want to add cloud capabilities using AWS IoT.

We like the idea of the "Things shadow" but we are not sure if it will fit well with the existing architecture. So I have a few questions.

- Can the **thingname** space in the MQTT topic have further levels of MQTT granularity?
The cloud service needs to ability to publish to specific device using it's serial# as the identifier, while at the same time also addressing a specific channel. Each device needs to subscribe to a topic specific to it's serial#. So that it only get messages that are intended for that device.
All "Thing Shadow" topics have "$aws/things/**thingName**/shadow/update" layout. Can "thingname" be replaced with serial#/channelID. Where an additional / is used for further granularity.
- Can the Thing Shadow utilise a different payload structure, or does it specifically have to fit the JSON format described [here](https://docs.aws.amazon.com/iot/latest/developerguide/iot-device-shadows.html)
- If we have 100 channels to expose what's the best way to do this if we had to use the Thing Shadow. Would this mean we would have to subscribe to a single topic per channel?
- Can the Shadow API subscribe to a wild card for example "$aws/things/SerialNumber123/+/shadow/get/accepted". Where the wild card level (+) represent the channelID. I noticed in the SDK that "aws_iot_shadow_register_delta()" does the subscription to delta topic using the "ThingName" from ShadowConnectParameters_t::pMyThingName. Can I use a "ThingName" that looks like "123/+" To make the delta topic subscribe to all the channels with serial 123?
- How is the thing shadow stored on the device in JSON format? I am interested in understanding the memory requirements.

**Comment by gordonwang0** [comment]
Hi @umanayana,

* Unfortunately, the Shadow service doesn't seem to work if your thing name contains a `/`.  ThingName is supposed to correspond to a single device.  I suggest doing something like the following to distinguish devices and channels:

Use the topics `$aws/things/123/shadow/...` to identify devices (where `123` is the serial number).
Use the keys in the JSON document to identify channels.  An example for device `123`:
```json
{
    "state": {
        "reported": {
            "channel1": { ... },
            "channel2": { ... }
        }
    }
}
```
Then use a JSON parser to get data from each channel.

* The Thing Shadow must follow the JSON format described in the docs.
* I would suggest subscribing to a single topic per device and placing the channels in the JSON doc, as above.
* No, you will not be able to use a thing name with a wildcard "+" in it.
* This depends on your application.  To keep the JSON document small, I recommend only publishing the data of a few channels at a time.  The data will be combined in the cloud into a single large document.  When fetching the shadow, you can use [the rules engine to trim topics](https://docs.aws.amazon.com/iot/latest/developerguide/using-device-shadows.html#device-shadow-trim-messages) for single channels so that you don't have to receive a large shadow document from the cloud.

**Comment by gordonwang0** [comment]
Hi @umanayana,

Please let me know if you need any more help with this.  Closing issue.
