### ISSUE TITLE
When will OTA be supported ?

### ISSUE THREAD

**Issue by puppies** [aws/aws-iot-device-sdk-embedded-C#226]
Hi,
I almost finish my product except the OTA function.  So i want to know, is there a plan to support OTA ?

**Comment by lt72** [comment]
Hi @puppies, Amazon FreeRTOS supports *secure* OTA updates as of last week. OTA on Amazon FreeRTOS also include a secure bootloader that has been tested on most supported HW.
For the C-SDK, writing a secure boot loader would need many extension points and would need additional design work on top of what Amazon FreeRTOs offers today. That is of course, because we do not control the underlying RTOS.
We are not currently offering OTA for C-SDK, and we have no concrete plan or date to deliver one I can share at this time.. 
That said, we are recording your request and we will prioritize accordingly.

**Comment by lt72** [comment]
Closing this issue, please re-open if you need more info.
