### ISSUE TITLE
Unable to connect when running with valgrind

### ISSUE THREAD

**Issue by jeremyhahn** [aws/aws-iot-device-sdk-embedded-C#23]
When I start up my application using valgrind `aws_iot_shadow_connect` always returns -1.

When I start up without valgrind, it connects fine.

**Comment by liuszeng** [comment]
Hi @jeremyhahn ,

Thank you very much for using AWS IoT Embedded C SDK!

Could you please specify the version of the SDK you are using when you had the issue? Have you seen any debug messages printed out? It will be really helpful for us to know these information to duplicate the issue on our side.

Thanks,
Liusu

**Comment by liuszeng** [comment]
Hi @jeremyhahn ,

We are able to duplicate your issue. The detailed dependency information is listed below:

OS: Mac OS X EI Capitan v10.11.5
SDK: AWS IoT Embedded C SDK v2.0.0
Target sample: subscribe_publish_sample
Valgrind: valgrind v3.11.0
Connection type: MQTT TLSv1.2 Mutual Authentication with X.509 certificate

This is more like a Mac OS X related issue. Take the "subscribe_publish_sample" as a example, there are a few things you can do to fix this:

1. Increase mqttCommandTimeout_ms to allow more waiting time for the connect command since execution with valgrind adds up more delays onto the time sensitive MQTT connecting process. In `sample/linux/subscribe_publish_sample/subscribe_publish_sample.c : line161`:

        ...
        // mqttInitParams.mqttCommandTimeout_ms = 2000; // Origin
        mqttInitParams.mqttCommandTimeout_ms = 3000;
        ...

2. Force both the paramsQOS0.isRetained and paramsQOS1.isRetained to 0. AWS IoT currently does not support retained publishes  and will close the connection if the publish requests contained a set retained flag. Execution with valgrind on OS X may initialize the internal memory differently and set the flag. In `sample/linux/subscribe_publish_sample/subscribe_publish_sample.c : line 205, 209`:

        ...
        IoT_Publish_Message_Params paramsQOS0;
        paramsQOS0.qos = QOS0;
        paramsQOS0.payload = (void*) cPayload;
        paramsQOS0.isRetained = 0; // Added. Force to disable the retained publish
        ...
        IoT_Publish_Message_Params paramsQOS1;
        paramsQOS1.qos = QOS1;
        paramsQOS1.payload = (void*) cPayload;
        paramsQOS1.isRetained = 0; // Added. Force to disable to retained publish
        ...


Please confirm if we share the same context with you here and do let us if the above fixes the issue. We appreciate your inputs for making our SDK better.

Thanks,
Liusu

**Comment by jeremyhahn** [comment]
My development environment is Linux Mint 17. I'll try your suggestions and report back.

**Comment by jeremyhahn** [comment]
Implementing your recommendations does not solve the issue. It also appears that if I keep trying to start my app with valgrind, I get either a -1 or -28 error code. It's not consistent.

Valgrind 3.10.1
SDK v2.0
Linux Mint 17
Connection Type: Shadow X509 cert

The last thing I see in a DEBUG message before getting the error is the "Peer certification information" after the verification is successfully completed.

**Comment by liuszeng** [comment]
Hi @jeremyhahn ,

Thank you very much for the information provided. It seems that the TLS handshake process gets through while the command itself has got some issue. Error code -28 indicates a timeout happened for the TLS request to complete. Please verify the following:

1. Are you still constantly seeing this issue without any successful connect attempt?
2. What is the current configuration of mqttCommandTimeout and  you have in the example? Can you increase the mqttCommandTimeout_ms more and try again?

Thanks,
Liusu

**Comment by jeremyhahn** [comment]
I was able to resolve the `aws_iot_mqtt_connect` timeout issue by increasing `mqttCommandTimeout_ms` but the problem remains for my shadow connection. How do I increase the timeout for that connection as well?

**Comment by liuszeng** [comment]
Hi @jeremyhahn ,

Glad to know that you got the basic subscribe/publish sample working with valgrind.

In the latest v2.0.0, for shadow examples `samples/linux/shadow_sample` and `samples/linux/shadow_sample_console_echo`, the detailed configurations of the AWS_IoT_Client are hidden inside `aws_iot_shadow_init` function call in the sample code for simplicity. To modify the default configurations, you can find `mqttCommandTimeout_ms` in `src/aws_iot_shadow.c` line 66. In this way, you should be able to run the shadow sample using valgrind.

Please let us know how it goes.

Thanks,
Liusu

**Comment by jeremyhahn** [comment]
That did it, thanks!
