### ISSUE TITLE
Subscribe not working in subscribe_publish_example

### ISSUE THREAD

**Issue by atyshka** [aws/aws-iot-device-sdk-embedded-C#278]
I'm trying out the pub-sub example, and the subscriber doesn't seem to be working. Everything connects fine, then I get the following output:
```
Subscribing...
-->sleep
-->sleep
-->sleep
-->sleep
-->sleep
-->sleep
```
I just keep getting sleep without the subscribe callback. From the IoT dashboard I can see that the publish is working fine, and I can also see that the subscriber is connected:
![screenshot from 2019-02-19 13-33-58](https://user-images.githubusercontent.com/19317207/53039019-225a1a80-344c-11e9-81bd-44c7c5e45989.png)
But I get nothing but "sleep" in the terminal output, implying the callback isn't working. Any advice? I'm using the default code with no modifications except my certificate config. Also will mention that subscribe is enables for all topics in the policy

**Comment by yuhui-zheng** [comment]
Hi atyshka,

You seem to have IoT policy configuration issue. In order to run MQTT pub-sub example (e.g. ```/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample```) , you need to have these policies ```iot:Connect```, ```iot:Publish```, ```iot:Subscribe```, ```iot:Receive``` attached to your Thing. (In my setup, if I remove ```iot:Receive```, I get the exact console print.)

Please also refer to [AWS IoT Policy Actions](https://docs.aws.amazon.com/iot/latest/developerguide/policy-actions.html).

**Comment by atyshka** [comment]
Yes, the receive was my issue. Would be great to have this in the readme!
