### ISSUE TITLE
Which Communication protocol is effective to use in IOT ??. MQTT or HTTP ?

### ISSUE THREAD

**Issue by siva551993** [aws/aws-iot-device-sdk-embedded-C#280]
Hi All ,

          Which  communication protocol( MQTTs or HTTPs) can be effective  when  iot device (cc3220sf ) connects to Aws IOT Core??.

          Please provide the Opinion and Suggestion when comparing  MQTTs or HTTPs protocol for IOT device communication to the AWS IOT Cloud.

**Comment by lt72** [comment]
Hi @siva551993, here is a page from the documentation that can help decide: https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html

When connecting from a micro-controller, generally speaking, MQTT is less CPU and memory intensive. For that reason, MQTT is preferred with both the C-SDK (this repo) and [Amazon FreeRTOS](https://github.com/aws/amazon-freertos). 

If you explain your scenario in more details, we _may_ have a better, more targeted, set of suggestions.

**Comment by siva551993** [comment]
Hi Lorenzo Tessiore ,

               Thanks for Your response.

               Let assume a scenario, 
               We need to connect to the 1000 IOT device every year to the AWS IOT Core via  GPRS interface from the IOT End device. 
               There is a need to select  Communication protocol(MQTTs or HTTPs) in such a way that it should be communicated to the IOT Core effectively with optimized running cost and with optimized performance.

               Kindly provide the suggestion in the following aspects  about which protocol(MQTTs or HTTPs) to choose,
         
                       1. Optimized GPRS Data Consumption in the End Device
                       2. Response time 
                       3.  IOT End device CPU Overhead ( Controller CC3220SF )
                       4. Throughput

**Comment by lt72** [comment]
Hi @siva551993, the data you asking about we currently do not currently measure. 
Because HTTP is stream oriented, an MQTT is message oriented, you may have better response time with MQTT, but larger throughout with HTTP. MQTT has less overhead though, so it may give you better data consumption. 
Please keep in mind that these are just guesses, but really one should test this assumption through prototyping and measuring for a well specified scenario. Sorry I cannot be more helpful at this time.
