### ISSUE TITLE
mbedtls_ssl_handshake in network_mbedtls_wrapper takes a long time without yield

### ISSUE THREAD

**Issue by thehellmaker** [aws/aws-iot-device-sdk-embedded-C#282]
I use esp32 and I use this library to connect to aws IOT. The framework I use is https://github.com/espressif/arduino-esp32. 

In the loop function I call _aws_iot_mqtt_internal_connect which inturn calls mbedtls_ssl_handshake which takes about 7 seconds for the handshake. the general suggestion for a watchdog timer is about 5seconds and the loop should run within 5 seconds. Considering this mbedtls_ssl_handshake should yield during this connection establishment time. 

Opening this bug where the library which doesn't yield during connection establishment which could potentially trigger watchdog timeout

**Comment by lt72** [comment]
Hi @thehellmaker, we do not support arduino-esp32 directly, but rather our partners at Espressif do. 
I would suggest opening this same issue in the https://github.com/espressif/arduino-esp32 and asking for guidance, while at the same time increasing the watchdog timer timeout. 
Establishing a connection is implemented as a 'blocking' call, because there is really not much one can do before the connection is established, so it makes sense for it to be blocking. 
I am not familiar with the arduino-esp32 implementation, but 7 secs seems like a lot. Worth checking directly with Espressif in my opinion.

**Comment by gordonwang0** [comment]
Hi @thehellmaker,

Please let us know if you need any more help with this.  Closing issue.
