### ISSUE TITLE
AWS SDK sample getting stuck before connection

### ISSUE THREAD

**Issue by surathmu** [aws/aws-iot-device-sdk-embedded-C#301]
The below is my execution and it does not proceed beyond the point its stated below. Please suggest fix.

pi@raspberrypi:~/sdk/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample $ ./subscribe_publish_sample

AWS IoT SDK Version 3.0.1-

DEBUG:   main L#159 rootCA /home/pi/sdk/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample/../../../certs/root-CA.pem
DEBUG:   main L#160 clientCRT /home/pi/sdk/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample/../../../certs/00bfdebd3c-certificate.pem.crt
DEBUG:   main L#161 clientKey /home/pi/sdk/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample/../../../certs/00bfdebd3c-private.pem.key
Raja Connecting...
DEBUG:   iot_tls_connect L#130
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#138   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#144  ok (0 skipped)

DEBUG:   iot_tls_connect L#146   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#159  ok

DEBUG:   iot_tls_connect L#161   . Surath Connecting to a22j5sm6o3yzc5.iot.us-east-1.amazonaws.com/8883...

**Comment by yuhui-zheng** [comment]
From the log lines, seems application is able to load certs, but failed to connect to IoT endpoint via port 8883. There can be multiple causes to symptom, and I'm listing a couple mostly likely causes below. 

1. Endpoint  
It seems you are trying to talk to "legacy" endpoint, instead of ATS (Amazon Trust Service) endpoint. Please check your AWS IoT Core console (AWS IoT -> (left panel) Settings -> ) and confirm you are using the endpoint suggested in that page. Please also confirm your AWS region is what you intended, which is us-east-1 from above log. 

2. Root Cert 
Once endpoint is confirmed, please also check the CA root cert used. If ATS endpoint, you may need to update CA root cert. See this page https://docs.aws.amazon.com/iot/latest/developerguide/managing-device-certs.html. 

3. Thing Policy
With (1) and (2), client side configuration should be correct. Policy attached to Thing needs to allow "connect" from server side as well. In order to run subscribe_publish_sample example, you need all four MQTT policies mentioned in this page. 
https://docs.aws.amazon.com/iot/latest/developerguide/policy-actions.html

In the case of above does not resolve your issue, please circle back.

**Comment by surathmu** [comment]
Thank you of updating back. Changed the host name to the one mentioned in my aws console

#define AWS_IOT_MQTT_HOST              "ateqttstzv0c-ats.iot.us-east-2.amazonaws.com" ///< Customer specific MQTT HOST. The same will be used for Thing Shadow

But still i get following error while connecting from SDK.

DEBUG:   iot_tls_connect L#161   . Surath Connecting to ateqttstzv0c-ats.iot.us-east-2.amazonaws.com/8883...
Entering into mbedtls_net_connectDEBUG:   iot_tls_connect L#168   . Surath Connecting to ateqttstzv0c-ats.iot.us-east-2.amazonaws.com/8883...
ERROR: iot_tls_connect L#169  failed
  ! mbedtls_net_connect returned -0x52

**Comment by surathmu** [comment]
Is this a DNS issue in raspberry pi board. Please guide how to get rid of this issue.

**Comment by surathmu** [comment]
Latest I am getting the following error after making some changes.

DEBUG:   _iot_tls_verify_cert L#49
Verify requested for (Depth 1):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 06:7F:94:57:85:87:E8:AC:77:DE:B2:53:32:5B:BC:99:8B:56:0D
issuer name       : C=US, O=Amazon, CN=Amazon Root CA 1
subject name      : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
issued  on        : 2015-10-22 00:00:00
expires on        : 2025-10-19 00:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=true, max_pathlen=0
key usage         : Digital Signature, Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   Surath This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49
Verify requested for (Depth 0):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 02:23:BF:9C:05:8C:DE:41:B6:A1:E5:F5:E5:7C:6B:5F
issuer name       : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
subject name      : CN=*.iot.us-east-2.amazonaws.com
issued  on        : 2018-08-02 00:00:00
expires on        : 2019-08-02 12:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=false
subject alt name  : *.iot.us-east-2.amazonaws.com, iot.us-east-2.amazonaws.com
key usage         : Digital Signature, Key Encipherment
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

DEBUG:   _iot_tls_verify_cert L#54   Surath This certificate has no flags

ERROR: iot_tls_connect L#237  failed
  ! mbedtls_ssl_handshake returned -0x2700

ERROR: iot_tls_connect L#244     Unable to verify the server's certificate. Either it is invalid,
    or you didn't set ca_file or ca_path to an appropriate value.
    Alternatively, you may want to use auth_mode=optional for testing purposes.

ERROR: main L#190 Error(-4) connecting to aateqttstzv0c-ats.iot.us-east-2.amazonaws.com:8883

**Comment by yuhui-zheng** [comment]
Error code -0x2700 suggests "certificate verification failed." 

mbed TLS x509.h -- ```#define MBEDTLS_ERR_X509_CERT_VERIFY_FAILED               -0x2700  /**< Certificate verification failed, e.g. CRL, CA or signature check failed. */```

In one of your posts above, you mentioned you are using VeriSign root cert, which may not work well with ATS endpoint you are currently using. I'd suggest download one of the four certs under "Amazon Trust Services Endpoints (preferred)" in below link https://docs.aws.amazon.com/iot/latest/developerguide/managing-device-certs.html


--------- some other tricks --------
You seem to have a rough time figuring out the right combination of endpoint/port/certs/key. To have some confidence before inputting the combination to C-SDK, you could play with "openssl s_client" command. An example -- 
```openssl s_client -connect <your-end-point>:<port> -CAfile <path-to-ca-root-cert> -cert <path-to-client-cert>  -key <path-to-client-private-key> -state``` 

openssl s_client man page -- https://www.openssl.org/docs/manmaster/man1/s_client.html

**Comment by surathmu** [comment]
Not able to connect even after taking from this link no of the CAs work.
 https://docs.aws.amazon.com/iot/latest/developerguide/managing-device-certs.html

openssl command works successful with the same parameters.

Please guide.

**Comment by yuhui-zheng** [comment]
Could your share your error message printed out on terminal? 


Also, this repo is mostly about configuration on client side. In order to "talk" to AWS IoT cloud from a client, AWS IoT policy also needs to be configured correctly. (In a more general description, server side needs to be configured to authorize client to connection, message subscription, publish, and receive.) Please let us know if above doesn't sound familiar to you...

**Comment by surathmu** [comment]
I did it every steps fresh and device got connected to aws successfully. Thanks a lot for your guidance.
