### ISSUE TITLE
Invalid JSON Array of Responses Received

### ISSUE THREAD

**Issue by crazenator** [aws/aws-iot-device-sdk-embedded-C#303]
It has been observed that the callback receive invalid JSON array (comma  missing between response elements). This happens for multiple responses received in JSON; any idea what is going on or a way to fix it...

**Comment by lt72** [comment]
Hi @crazenator, we would need some more details to start investigating. Could you please send us more details about your scenario and possibly a log of the execution and the broken JSON document?

**Comment by crazenator** [comment]
Sure.
So, I've multiple topics on which I've subscription. The message in the callback contains JSON responses from topics in an array which is not proper JSON array (comma missing between elements). For example A is the JSON response for topic-1 and B is the JSON response from topic-2; if I receive the message simultaneously in callback, it is formatted as following
`[A B]`
while it's expect to be
`[A, B]`
Let me know if you need more details. Thanks

**Comment by yuhui-zheng** [comment]
Hi @crazenator, 

JSON string is parsed with a 3rd party library [JSMN](https://github.com/zserge/jsmn/blob/master/jsmn.c). In this case, the function of interest is [jsmn_parse()](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/external_libs/jsmn/jsmn.c#L181).

I'm guessing you are using Shadow? Are you observing failure in our source code (under ```aws-iot-device-sdk-embedded-C/src/``` maybe in ```aws_iot_shadow_json.c```), or having some issue consuming the parsed JSON in your application code? Trying to narrow down how to better assist from my side...

**Comment by crazenator** [comment]
I receive the JSON in callback, registered with AWS job (`aws_iot_jobs_subscribe_to_all_job_messages`). I printed the received message and it was invalid JSON array, as mentioned above.

**Comment by yuhui-zheng** [comment]
Apologies for the delay. We are currently investigating this issue from the server side. Will circle back once there's an update.

**Comment by crazenator** [comment]
Sure, let me know if you need any information from my side.

**Comment by yuhui-zheng** [comment]
@crazenator  I guess this post is more of some thought instead of concrete conclusion on what happened... To summarize, confirmed server responded with valid JSON string (before ```jsmn_parse()``` things are fine). What you are experiencing may be related to JSON parsing in collaboration with application code (not vended by this repo). It would be easier to for us to look at the parsing logic to further aid. 

-------- some evidence collected --------
To start with, handler type of ```pApplicationHandler``` for ```aws_iot_jobs_subscribe_to_all_job_messages()``` interface is not provided by this repo. It's more or less up to user to define how to parse JSON string from server. Though, in ```jobs_sample.c``` under ```/samples/linux/jobs_sample/```, sample handles are provided for reference. (e.g. [```iot_get_pending_callback_handler()```](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/samples/linux/jobs_sample/jobs_sample.c#L65), in which we first initialize JSMN parser, then parse the string with ```jsmn_parse()```.)

Our suspicions after reading through your post were:
1. Was this server issue, that when server responded back with multiple topics a comma was missing in JSON string?
2. Was this JSON parser issue, that JSON array is incorrectly returned?

(1) was proved to be NOT the case. 
Callback handler

```
static void iot_get_all_job_callback_handler(AWS_IoT_Client *pClient, char *topicName, uint16_t topicNameLen, IoT_Publish_Message_Params *params, void *pData) {
	IOT_INFO("\nJOB GET ALL JOBS callback");
	IOT_INFO("print everything: %s", (char *)params->payload);
}
```
JSON string from terminal
```
{"timestamp":1551921763,"jobs":{"QUEUED":[{"jobId":"example-job-01","queuedAt":1551921179,"lastUpdatedAt":1551921179,"executionNumber":1,"versionNumber":1},{"jobId":"example-job-02","queuedAt":1551921190,"lastUpdatedAt":1551921190,"executionNumber":1,"versionNumber":1},{"jobId":"example-job-03","queuedAt":1551921202,"lastUpdatedAt":1551921202,"executionNumber":1,"versionNumber":1}]}}
```
Which could confirm with online JSON validator that it's a valid JSON. (The focus was to confirm comma between nested components. You may see some escape token at the end of the string.)

To reproduce (2) and maybe difficulties you are experiencing, I think it would be easier for us to look at the parsing logic.

**Comment by yuhui-zheng** [comment]
Hi @crazenator, I'm assuming you are unblocked and closing this thread. Please contact us, if you have difficulty getting things work.
