### ISSUE TITLE
AWS C-SDK OTA Question.

### ISSUE THREAD

**Issue by couperyork** [aws/aws-iot-device-sdk-embedded-C#331]
Hi there, not sure if this is the best place for this but...

I am using the ESP-ADF for a project which in turn uses this project's C-SDK for the AWS IOT libraries. I am looking to do OTA and utilize AWS and noticed it's available in Amazon FreeRTOS and there's a port of just the OTA libraries available for ESP32. What's the best route to integrate the Free RTOS OTA port libraries into this SDK (say) so it can then be used with the ESP-ADF/IDF if it's possible? or am I better to just go down the route of using the ESP-IDF HTTPS OTA. 

Any advice is appreciated.

Cheers!

**Comment by lt72** [comment]
HI @couperyork, we are in the process of testing the beta release of C-SDK v4 for on this repo. (see [v4_beta ](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/v4_beta) branch). 
The C-SDK v4 will be the same set of libraries running on the next version of FreeRTOS (see [feature/ble-beta](https://github.com/aws/amazon-freertos/tree/feature/ble-beta) branch for Amazon FreeRTOS repo, where we have the same libraries in beta as well, plus BLE support as well).
We are planning to release sometimes in the next few months, I cannot give you a precise date yet. 
OTA is for now only available on Amazon FreeRTOS, although it could be available on C-SDK at some point in time.

All that said, I would say that:
- if you want to use FreeRTOS and a board/SoC that is supported on Amazon FreeRTOS, you may want to use the Amazon FreeRTOS distro immediately.
- if the above is not true, then you should consider porting the OTA library.

The OTA library in the feature/ble-beta branch is already working on the same MQTT library that this repo will support (the plan is to unify C-SDK and FreeRTOS libraries...). Still you will  need to implement the OTA library abstraction layer for your target HW. [Here ](https://github.com/aws/amazon-freertos/tree/feature/ble-beta/lib/ota/portable)are some examples and the docs for [porting](https://docs.aws.amazon.com/freertos/latest/userguide/porting-ota-pal.html). You may also find the FreeRTOS[ porting and qualification](https://docs.aws.amazon.com/freertos/latest/userguide/porting-guide.html) guide useful.

If you give me more details about your target HW, I may be able to guide you better.

**Comment by couperyork** [comment]
Hi @lt72 ,

Thank you for your quick response! 

That's great information to know. An excellent idea to unify the library set.

My HW is a ESP32-WROOM-32 which I see there is a port for, so it's just a matter of plonking that port into my ESP-IDF project and referencing/accessing it similar to how the FreeRTOS demo runner does or is there quite a few FreeRTOS libs I'll need to pull in also? 

It's worth noting that I have successfully got my ESP subscribe/publishing to AWS using this SDK inside the ESP32-IDF.

Thanks again!

**Comment by lt72** [comment]
Hi @couperyork, In a way, you setup is the worst and the best at the same time ;-) Because you already got the v3 C-SDK working already on your HW, the best scenario for you would be to keep going. 
But, if you want to use OTA and the latest libraries, the easiest way is to start from the FreeRTOS repo and move over your app from the ESP-IDF to use the ESP-IDF inside FreeRTOS. You'll find the same ESP-IDF pretty much, may be one version behind or so... 
Moving Amazon FreeRTOS repo to work inside your existing ESP-IDF project could be a lot of work for the simple reason that OTA has a LOT of dependencies and you'll end up having to move over a lot of files, which will take time and also create a maintenance burden. 
I would recommend to try and move over your app to the FreeRTOS repo. It seems easier (less files, less dependencies issues).

**Comment by couperyork** [comment]
Thanks for the advice, that should be a good compromise. Should be interesting since my project uses the ADF which wraps around it's own version of IDF (currently version 3.1 from November 2018), So kinda two ports in one here 😅.

**Comment by abhidixi11** [comment]
Hello @couperyork ,
I'm closing this issue, let us know if you have any further questions.
