### ISSUE TITLE
ACK not sent back to a received packet with QoS1

### ISSUE THREAD

**Issue by husigeza** [aws/aws-iot-device-sdk-embedded-C#358]
Hello,

It can happen, that a packet received with QoS 1 successfully read and processed (topic specific, user registered callout called), but the ACK belonging to it is not sent back because the timeout value passed to aws_iot_mqtt_yield() expires before sending back the ACK. On the server side this results re-sending the packet, and on the client side it causes confusion because packets containing the same data is received several times.
In my opinion for QoS1 packets the ACK always should be sent back no matter of the timer.

**Comment by gordonwang0** [comment]
Hi @husigeza,

Thanks for bringing this up.  I'll leave this issue open for further evaluation.  However, we are currently focusing efforts on the v4 release, so the resolution for this may be delayed.

**Comment by Robotmad** [comment]
We suffered the same issue as we had set a very short timeout.
In most of the code when there is something specific to do a longer timeout is employed already but not in `aws_iot_mqtt_internal_send_packet()` which just uses the mqtt_yield timeout.
Fix for us was to use the commandTimeoutMs value for the call to `write()`.
To be flexible about it we used the max of the two timeouts in case in some scenarios the mqtt_yield timeout had been set higher - hence:

`	uint32_t original_timeout = pTimer->timeout;
	pTimer->timeout = max(pTimer->timeout, pClient->clientData.commandTimeoutMs);
	
	while(sent < length && !has_timer_expired(pTimer)) {
		rc = pClient->networkStack.write(&(pClient->networkStack),
						 &pClient->clientData.writeBuf[sent],
						 (length - sent),
						 pTimer,
						 &sentLen);
		if(SUCCESS != rc) {
			/* there was an error writing the data */
			break;
		}
		sent += sentLen;
	}
	
	pTimer->timeout = original_timeout;	// Restore original timeout
`

**Comment by Crzyrndm** [comment]
Just hit this issue when a developer added IO work to a QoS1 subscription (which is a problem in itself, but anyway). This is made somewhat more complicated to debug by the return of an uninitialised variable (aws_iot_mqtt_internal_send_packet -> rc) when the timer is expired before send is attempted (and this is not the only place where this occurs).

Like @Robotmad I was surprised to find that the yield timer was being used here instead of a seperate send timer (like most other locations). This means this particular issue could occur even with a well behaved callback if it was received late enough in the yield cycle (unlikely in my case as network IO is glacially slow, but still a possible cause of random/unexpected failures).

**Comment by gordonwang0** [comment]
Hello,

This has been resolved in #699.  Closing issue.
