### ISSUE TITLE
Cross Compile AWS IoT Embedded C SDk

### ISSUE THREAD

**Issue by agilesai1294** [aws/aws-iot-device-sdk-embedded-C#435]
Hi,

Can anyone provide me with the steps on how to cross compile Embedded C SDK using arm-none-linux-gnueabi-gcc?

**Comment by lt72** [comment]
Hi @agilesai1294, the C-SDK does not directly support cross-compiling for a ARM target. Although we may be adding this feature sometimes in the near future we cannot offer you a solution in the short term.
The C-SDK is compiled and tested for Linux only. 
The reason is that the C-SDK is meant to be embedded into another SDK (such as the one provided by the silicon vendors for your own development board). 
My suggestion is for you to start from the SDK or tool chain for your target HW, and add the C-SDK files to the build system of your target HW.

**Comment by yuhui-zheng** [comment]
@agilesai1294 Please reach out again if you have further issue integrating C-SDK with targeted platform. I'd close this thread for now.

**Comment by agilesai1294** [comment]
Hi @lt72 If i want to test pubsub in my target HW. what all dependent files do I need to port?

**Comment by lt72** [comment]
You will need to fill the implementation for platform abstractions here: (note: only in v4_beta branch)
https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/v4_beta/platform/ports/template 
For network, you can recycle OpenSSL port or mbedTLS ports here:
https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/v4_beta/platform/ports/posix/source 
https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/v4_beta/platform/network

**Comment by agilesai1294** [comment]
Hi @lt72 
I tried cross compiling using the following command:
cmake  .. -DCMAKE_C_COMPILER=/home/bharath/CodeSourcery/Sourcery_G++_Lite/bin/arm-none-linux-gnueabi-gcc

It successfully completes cmake and when i tried to make after cmake. I got the following error. Can you please tell me what should I change to make it work with arm-none-linux-gnueabi-gcc compiler
![Capture1](https://user-images.githubusercontent.com/34946584/58662189-9469b780-82f7-11e9-9fb3-b487eee1bbba.PNG)

**Comment by lt72** [comment]
Hi @agilesai1294, as a matter of fact this is actually part of our roadmap and we may have a solution faster than we can agree and implement all necessary steps, if you can wait a couple of days.

**Comment by agilesai1294** [comment]
Hi, @lt72 Is the solution ready for cross compiling this SDK with arm-linux-gnueabi-gcc?

**Comment by lt72** [comment]
Not yet. 
@gordonwang0: can we give @agilesai1294 what we have so far for cross compiling? Would that be useful?

**Comment by gordonwang0** [comment]
Hi @agilesai1294,

In addition to setting the compiler, you will also have to port the SDK to your platform.  The errors you're seeing are because the SDK is trying to build with the POSIX port but can't find the POSIX functions.

Ports of the SDK are implemented in the [ports](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/v4_beta/platform/ports) directory.  You can set the port to use by setting the CMake variable `IOT_PLATFORM_NAME`.

`cmake .. -DCMAKE_C_COMPILER=/home/$USER/CodeSourcery/Sourcery_G++_Lite/bin/arm-none-linux-gnueabi-gcc -DIOT_PLATFORM_NAME=template`

The command above allows you to build with the "template" port, which is empty function stubs.  Once you have that building, you should implement your port based on the directions in the template.

**Comment by dcgaws** [comment]
@agilesai1294 please reopen this if the above issue did not unblock you.
