### ISSUE TITLE
Error during compilation: libmbedcrypto.a not found

### ISSUE THREAD

**Issue by Lakshana3** [aws/aws-iot-device-sdk-embedded-C#509]
> gcc: error: ../../../external_libs/mbedTLS/library/libmbedcrypto.a: No such file or directory
> Makefile:63: recipe for target 'all' failed
> make: *** [all] Error 1
> 

I couldn't find 'libmbedcrypto.a' file anywhere. What should I do?

**Comment by gordonwang0** [comment]
Hi @Lakshana3,

Which target are you trying to build?  Could you post the full build logs?

Mbed TLS is a third-party library not included in this repository.  You will need to download mbed TLS and build it; instructions are [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/master/external_libs/mbedTLS).

**Comment by gordonwang0** [comment]
Hi @Lakshana3,

Please comment/reopen this if you need any more help.  Closing issue.

**Comment by ReedsHorton** [comment]
I had the exact same issue and solved it by downloading from [https://tls.mbed.org/](url) instead of downloading from [https://github.com/ARMmbed/mbedtls](url) as suggested in [https://docs.aws.amazon.com/iot/latest/developerguide/iot-embedded-c-sdk.html](url). I see there is a note about unstable dev branches but maybe the wording there could be more clear about which repo should be used...
