### ISSUE TITLE
Updating MQTT Stack to align with AWS Embedded 2.1.1

### ISSUE THREAD

**Issue by kjordan-sa** [aws/aws-iot-device-sdk-embedded-C#60]
Is there a plan to update to the newest AWS stack (https://github.com/aws/aws-iot-device-sdk-embedded-C). I am looking to make sure that this stays inline with any changes that Amazon may make.

**Comment by fengsongAWS** [comment]
Hi @kjordan-sa ,

Thanks for your interest in AWS IoT Device SDK. Yes, the SDK team is actively working on all the SDKs to make sure the performance and functionality updated. Embedded C is one of the most important one in our road map. Please stay tuned.

Thanks,
Fengyi

**Comment by chaurah** [comment]
Hi @kjordan-sa,
     Are there any specific features that you think are completely missing? I want to be sure that we are prioritizing things properly so please do let us know.

Rahul

**Comment by kjordan-sa** [comment]
I have been having issues with connection and disconnection as well as some odd ball issues with SSL authentication for topic subscription but not topic publishing.

I am mainly looking into the connect and disconnect though. Having

**Comment by chaurah** [comment]
Have you tried anything specific to resolve these issues? None of these should be due to the SDK itself. For tracking connect and disconnect you can use either the IoT [Lifecycle events](http://docs.aws.amazon.com/iot/latest/developerguide/life-cycle-events.html) or use LWT messages. Have you tried setting up Cloudwatch to see server side logs?

Rahul
