### ISSUE TITLE
Unit Test Fails in Buffer Small scenarios

### ISSUE THREAD

**Issue by techguyzz** [aws/aws-iot-device-sdk-embedded-C#637]
Hi,

The following file https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/tests/unit/src/aws_iot_tests_unit_jobs_json.c 

has garbage data in Line 95 which affects execution.

> char buffer[11];

Also string compare in the Line 105

> CHECK_C(strncmp(defaultUpdateRequestSerialized, buffer, 9) == 0);

fails everytime executing the Unit Test.

**Comment by lundinc2** [comment]
Hello @techguyzz,

Thank you for bringing our attention to this issue. I will investigate and get back to you.

**Comment by abhidixi11** [comment]
Hello @techguyzz,
The problem is not the garbage data. 
On line 99 (see below) function aws_iot_jobs_json_serialize_update_job_execution_request() is expected to copy serialized data into the buffer. 
https://github.com/aws/aws-iot-device-sdk-embedded-C/blame/312af9a964dc0866877c0c27f8dc29c8434ce667/tests/unit/src/aws_iot_tests_unit_jobs_json.c#L99

But if aws_iot_jobs_json_serialize_update_job_execution_request()  fails to copy data into buffer, you will see garbage uninitialized data in there. 

Which platform did you test this on ?
Can you please check if call to vsnprintf() is failing in your case while stepping through the code ?

**Comment by techguyzz** [comment]
Hello @abhidixi11 

I checked with ARM platform with default internal svnprintf() of toolchain none-eabi gcc version 4.5.1

Is it working for you, in case the buffer is filled with random bytes of data ?

**Comment by abhidixi11** [comment]
Hello @techguyzz,
Thanks for the response. It is not filled with random bytes of data. As I mentioned earlier the buffer is uninitialized and aws_iot_jobs_json_serialize_update_job_execution_request() is responsible for filling it with the correct data. 
The reason you are seeing random byte is most likely because  vsnprintf() is failing. 
Here is the sequence:
aws_iot_jobs_json_serialize_update_job_execution_request() ->_printKey() ->_printToBuffer()->
vsnprintf() (https://github.com/aws/aws-iot-device-sdk-embedded-C/blame/d039f075e1cc2a2a7fc20edc6868f328d8d36b2f/src/aws_iot_jobs_json.c#L42)
I does work on Linux. 
If you can find out which step is failing in above sequence, we may able to help.
Thanks.

**Comment by yuhui-zheng** [comment]
Please create another issue, if further question.
