### ISSUE TITLE
TLS timeout before reading entire payload

### ISSUE THREAD

**Issue by danfriebe** [aws/aws-iot-device-sdk-embedded-C#653]
We have recently increased the size of the payload being sent to devices (> 100kb < 128kb) and have started to receive TLS timeouts before the entire payload is read.

We have tried a number of different buffer size and timeout/yield configurations
Currently using v3.0.1 of the C SDK
Multithreading is enabled

Sample debug output from SDK:
(offset 4, size 130906, readBufIndex 4, byteToRead 130906) TimeLeft_ms 135
WARN:  iot_tls_read L#340 Timer expired with 48990/130906 remaining

(offset 4, size 130906, readBufIndex 4, byteToRead 130906) TimeLeft_ms 499
WARN:  iot_tls_read L#340 Timer expired with 81916/130906 remaining

(offset 4, size 130906, readBufIndex 4, byteToRead 130906) TimeLeft_ms 499
WARN:  iot_tls_read L#340 Timer expired with 126701/130906 remaining

**Comment by yuhui-zheng** [comment]
Hi danfriebe,

I was wondering whether you are on TT with a similar question, since the alias looked similar. If that's the case, I will shortly close this issue here as we've got you covered. 

For the sake of larger audience group, I'm going to copy-paste a couple of key points from TT. 
- [AWS IoT limits documentation](https://docs.aws.amazon.com/en_us/iot/latest/developerguide/limits-iot.html#iot-protocol-limits): 
> The payload for every publish request is limited to 128 KB. The AWS IoT service rejects publish and connect requests larger than this size.

Though this is for device-->service, the other direction should also apply in SDK. 

- In C-SDK v3.0.1, ```_ENABLE_THREAD_SUPPORT_``` macro  needs to be enabled in ```aws_iot_config.h``` to ensure thread safety. Further details could be found in this forum post -- https://forums.aws.amazon.com/thread.jspa?threadID=237345.

- We are still actively developing this version of C-SDK. In which, we have architecture changes, and issue fixes to v3.0.1. (e.g. the yield function in MQTT pub/sub is removed.) Customers are encouraged to take a look and evaluate.
