### ISSUE TITLE
IOT_NETWORK_USE_OPENSSL connection crash[v4.0.0 beta]

### ISSUE THREAD

**Issue by MrZhuGe** [aws/aws-iot-device-sdk-embedded-C#672]
Switch to IOT_NETWORK_USE_OPENSSL connection, it will now crash.
Ubuntu 18.04 and OpenSSL 1.1.1  11 Sep 2018

**Comment by MrZhuGe** [comment]
What I found is that the IotNetworkOpenssl_Cleanup function is not blocking, and the loop creating the connection causes

**Comment by MrZhuGe** [comment]
The reason is that the IotNetworkMbedtls_Cleanup function blocks waiting for the connection to return and the IotNetworkOpenssl_Cleanup function does not block waiting for the connection to return. Why don't these two functions do the same thing? And it is not mentioned in the Demo.

**Comment by dan4thewin** [comment]
Hi, @MrZhuGe .
Thank you for reporting this problem.  Would you please describe the steps to reproduce the problem?

**Comment by yuhui-zheng** [comment]
@MrZhuGe 

Is this what you are referring to?
mbed TLS -- https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v4_beta/ports/common/src/iot_network_mbedtls.c#L788-L791

OpenSSL -- https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v4_beta/ports/common/src/iot_network_openssl.c#L673

The main target we have had in mind is embedded devices running RTOS. (As oppose to embedded Linux with OpenSSL.) Though I agree with you that there shouldn't be inconsistency if we provide wrapper for two TLS libs out of box. Forwarding the thread to see if there is already a plan to bridge the gap.

**Comment by gordonwang0** [comment]
Hi @MrZhuGe,

`IotNetworkOpenssl_Cleanup` is meant to be a one-time cleanup function.  Per its documentation:

https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/5b0ea3893f2beea29e6a6dc8c382b625b0dd183d/ports/common/include/iot_network_openssl.h#L117-L118

If you are experiencing a crash in the network receive loop due to calling `IotNetworkOpenssl_Cleanup` when the network stack is still active, this is an API usage error.  Your application must call `IotNetworkOpenssl_Close` and `IotNetworkOpenssl_Destroy` on all network connections before calling `IotNetworkOpenssl_Cleanup`.

The OpenSSL network stack does have code to block and wait for the network stack to shut down in `IotNetworkOpenssl_Destroy`:

https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/5b0ea3893f2beea29e6a6dc8c382b625b0dd183d/ports/common/src/iot_network_openssl.c#L1037-L1038

The `pthread_join` call should wait for the network to exit before continuing.  Are you experiencing a crash even with a call to `IotNetworkOpenssl_Destroy`?  If so, could you provide a code sample?

**Comment by MrZhuGe** [comment]
Hi @gordonwang0 I used it according to the demo you provided.First I opened `IOT_NETWORK_USE_OPENSSL`,then after your demo runs, `IotDemoNetwork_Cleanup` is not blocked waiting for the connection to be disconnected.When `IOT_NETWORK_USE_OPENSSL` is closed, `IotDemoNetwork_Cleanup` is blocked and continues to execute after the connection is disconnected.

**Comment by gordonwang0** [comment]
Hi @MrZhuGe,

I just ran the MQTT demo (iot_demo_mqtt) using the OpenSSL library several times on Ubuntu 18.04.3 with OpenSSL 1.1.1, but did not see any crash.  If you are seeing a crash, could you provide a stack trace?

The behavior that `IotDemoNetwork_Cleanup` blocks when using mbed TLS but not when using OpenSSL is intended.  Differences in those two network stacks allow the OpenSSL implementation to clean up each connection in `IotNetworkOpenssl_Destroy`, but the mbed TLS implementation must wait to clean up all connections in `IotNetworkMbedtls_Cleanup`.

**Comment by MrZhuGe** [comment]
Hi @gordonwang0 Crash does not exist under correct use. It is only part of the Demo. The connection will exit immediately after the connection is established. This is the difference between using OpenSSL and mbed TLS. I added blocking after the connection was established. No problem.

**Comment by dcgaws** [comment]
Thank you for confirming.
