### ISSUE TITLE
Questions/Remarks on network_interface APIs

### ISSUE THREAD

**Issue by ygalblum** [aws/aws-iot-device-sdk-embedded-C#75]
Hello,

I have a couple of questions/remarks on the network_interface API:

1. The new API added the connection parameters to iot_tls_init but did not remove them from iot_tls_connect. What is the expected behavior?
2. If "struct Network" is allocated by the caller and already includes a field for the connection parameters,  why not pass them there?
3. Why do you define the APIs (other than iot_tls_init) as signed functions if you expect the implementer to set them as callbacks in the Network structure?
4. Changing tlsDataParams to be of type (TLSDataParams *) will remove the need to include network_platform.h and allow the implementer to keep its internal structure internal
5. I've seen some conflicting answers regarding your plans to provide the code for OpenSSL. Will you provide it? If yes, can you say when?

Thanks,
Ygal

**Comment by chaurah** [comment]
Hi @ygalblum,
I think most of your questions can be answered by one simply thing, the current structure is somewhat broken. Its a byproduct of us wanting to reduce dependance on the original third party library we were using and modifying things to make them slightly more sensible. We didn't go as far as we should have gone in fixing the design issues. We hope to have the various, obvious, design issues fixed in the next release which is why it is taking such a long time. For the current version however, answers to your questions are below:
1) You should never need to set the network init and correct params directly at the moment. The mqtt_init and mqtt_connect APIs should be used.
2) Struct network should ideally be allocated outside the mqtt instance completely. You are correct that its not an efficient way to do things.
3) The original shadow design required this callback structure, again a design issue. This will not be the case in the new design.
4) That does make sense. Our current intention, based on requests from customers, is to completely separate the Network layer from the MQTT implementation. This will be similar to our C++ Device SDK.
5) We already have a working internal implementation for an OpenSSL wrapper for the network layer. Unfortunately its tied to the larger SDK changes and you will need to wait for the official release. Its not possible for me to give you a timeline unfortunately at this moment.

I know the answers are probably not to your liking. We are working on improving the Embedded C SDK and we will have a new release out very soon. In the meantime, please give us feedback on what you would like to see the new SDK do. That is extremely important for us as we work on improvements.

Thank you for using AWS IoT.

Rahul
