### ISSUE TITLE
Can not receive callback after subscribe a topic

### ISSUE THREAD

**Issue by arthur-zou** [aws/aws-iot-device-sdk-embedded-C#776]
If the input parameter of topic name is a local variable when i call aws_iot_mqtt_subscribe in a custom function,then i can not receive callback when i call aws_iot_mqtt_yield out of the custom function.
It is because the topicName of messageHandlers only shallow copy instead of deep copy in function aws_iot_mqtt_internal_subscribe.
Could you change it from a pointer to an array?

**Comment by arthur-zou** [comment]
https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/40dd34b60a20cf6fe624c5f1581039266daacf74/src/aws_iot_mqtt_client_subscribe.c#L263

**Comment by qiutongs** [comment]
Hi,

The choice shallow copy was intentional due to memory usage concern. And it is documented here https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/40dd34b60a20cf6fe624c5f1581039266daacf74/include/aws_iot_mqtt_client_interface.h#L123

You might need to allocate the buffer for topic name in the application code or define it as global variable.

**Comment by qiutongs** [comment]
If you still have problem, please re-open this issue or create a new one.
