### ISSUE TITLE
When reconnecting I get: "mbedtls_x509_crt_parse returned -0x3e00 while parsing root cert"

### ISSUE THREAD

**Issue by js1972** [aws/aws-iot-device-sdk-embedded-C#785]
When the sdk tried to reconnect I'm receiving this certificate error. It tries 8 times and then gives up so any subsequent publish returns rc = -13.

When I start using the client it can connect just fine. Its only if its silent for longer than the keepalive and then tries to publish a message that the auto reconnect kicks in and gives this failure.

```
MQTT DisconnectAuto Reconnect is enabled, Reconnecting attempt will start nowDEBUG:   iot_tls_connect L#130 
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#138   . Loading the CA root certificate ...
ERROR: iot_tls_connect L#141  failed
  !  mbedtls_x509_crt_parse returned -0x3e00 while parsing root cert
```

Any ideas? I'm using the release branch. v3.0.1.

**Comment by aggarw13** [comment]
js1972@, are you still facing issues with re-connection?

**Comment by js1972** [comment]
The latest version of mbedTLS from here: https://tls.mbed.org/download. Version 2.16.4.

x509.h doesnt exactly define that error, but it does define this:
```
#define MBEDTLS_ERR_X509_FATAL_ERROR                      -0x3000  /**< A fatal error occurred, eg the chain is too long or the vrfy callback failed. */
```

I wonder if thats what it is but they are mising the trailing `0`. All there error numbers are 4 digits long so I think thats what it is.

**Comment by aggarw13** [comment]
The [API documentation](https://tls.mbed.org/api/pk_8h.html#a334a28580efaab3c749fdf1dde28feb8) of mbedTLS mentions `MBEDTLS_ERR_PK_FILE_IO_ERROR` as the `0x3e00` error. As it is an IO error, it could be a file permission or locked resource issue preventing the TLS stack from re-reading the file on re-connection attempts.

Can you try to debug the state of the root CA file at the time of re-connection?

**Comment by js1972** [comment]
I cannot find any sign of the cert file being locked. I have moved away from this and now using the python SDK version 2 for AWS IoT and it is working perfectly well and I don't get any cert related errors.

**Comment by ravibhagavandas** [comment]
Glad to know that it works for you with AWS IoT python SDK version 2. I am closing this issue. Please feel free to re-open if you have further questions regarding C-SDK.

**Comment by shrinivasragolu** [comment]
I am just pasting the issue, which I have already raised in the forum

Using release version of 3.0.1 AWS Iot SDK as a built static library for the sample application
Using the mbedtls version 2.16.3. Is it proper version to work with? or any other versions are needed
Using MQTT port 443 instead of 8883
Still I am getting same below issue. Even my sample application could not able to prints using IOT_DEBUG prints..

Please help me in resolving below issue
$ ./pubsub
DEBUG: iot_tls_connect L#130
. Seeding the[ 18.777657] random: pubsub: uninitialized urandom read (127 bytes read)
random number g[ 18.786413] random: pubsub: uninitialized urandom read (1024 bytes read)
enerator...
DEBUG: iot_tls_connect L#138 . Loading the CA root certificate ...
ERROR: iot_tls_connect L#141 failed
! mbedtls_x509_crt_parse returned -0x3e00 while parsing root cert

Thanks,
Srinivas.

--

**Comment by aggarg** [comment]
> Using the mbedtls version 2.16.3. Is it proper version to work with? or any other versions are needed.

It is tested with version 2.16.5. You can run the following commands to get it as mention here: https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/.travis.yml

```
# Get mbedtls.
wget -qO- https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.16.5.tar.gz | tar xvz -C external_libs/mbedTLS --strip-components=1

# Get CppUTest.
wget -qO- https://github.com/cpputest/cpputest/archive/v3.6.tar.gz | tar xvz -C external_libs/CppUTest --strip-components=1
```

Thanks.
