### ISSUE TITLE
Project setup with mbedTLS fails

### ISSUE THREAD

**Issue by EthanJWright** [aws/aws-iot-device-sdk-embedded-C#814]
I'm stepping through the tutorial to build the sample application and cannot get the subscribe_publish_sample to properly link against mbedTLS. I have tried:
1. git clone --recursive https://github.com/ARMmbed/mbedtls.git mbedTLS
2. downloading and untaring mbedtls-2.16.5-apache.tgz

Both of these I have put in the path:
aws-iot-device-sdk-embedded-C/external_libs/mbedTLS

When running make after following the first process, I get roughly 14 errors, all with the pattern:
```
compilation terminated.
In file included from ../../../include/network_interface.h:35,
                 from ../../../platform/linux/mbedtls/network_mbedtls_wrapper.c:23:
../../../platform/linux/mbedtls/network_platform.h:20:10: fatal error: mbedtls/platform.h: No such file or directory
 #include "mbedtls/platform.h"
```

When running make after the second process, I get the error:
```
make -C ../../../external_libs/mbedTLS
make[1]: Entering directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS'
make[2]: Entering directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS/library'
make[2]: Leaving directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS/library'
make[2]: Entering directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS'
make[2]: Leaving directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS'
make[1]: Leaving directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS'
gcc: error: ../../../external_libs/mbedTLS/crypto/library/libmbedcrypto.a: No such file or directory
make: *** [Makefile:65: all] Error 1
```

I'm currently troubleshooting but any help or updates would be appreciated.

**Comment by ravibhagavandas** [comment]
Its possible that the include path for mbedTLS is not set correctly.

Could you specify from which path you run the `make` command.
To compile `subscribe_publish_sample` you need to run `make` from within `samples/linux/subscribe_publish_sample/` folder.

**Comment by ravibhagavandas** [comment]
@EthanJWright 

We further debugged the issue and found following causes for the compilation error:

1. `git clone --recursive https://github.com/ARMmbed/mbedtls.git mbedTLS` build fails with error `mbedtls/platform.h: No such file or directory`.

This is because the header file location is changed in mbedTLS default development branch. So you might need to pick one of the released versions `2.16.*`  by cloning the tag, for example: 

` git clone --branch mbedtls-2.16.5 git@github.com:ARMmbed/mbedtls.git`

2.  Regarding `mbedtls-2.16.5`  build fails with error: `../../../external_libs/mbedTLS/crypto/library/libmbedcrypto.a: No such file or directory`

This is because our Makefile was changed to support a higher mbedTLS version `2.18.1` , where it expects `libmbedcrypto.a` to be under `crypto/library/`

- To fix this, you can either point to mbedTLS version `2.18.1` by checking out both mbedTLS and crypto modules as follows:

```
wget -qO- https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.18.1.tar.gz
wget -qO- https://github.com/ARMmbed/mbed-crypto/archive/mbedcrypto-1.1.1.tar.gz
```
and copying them to `external_libs/mbedTLS` and `external_libs/mbedTLS/crypto` folders respectively.

- Or you can still use version`2.16.5` but update `samples/linux/subscribe_publish_sample/Makefile` line 34 as follows:

`CRYPTO_LIB_DIR = $(MBEDTLS_DIR)/library`

We will work on a right fix for this mismatch in versions.

**Comment by abhidixi11** [comment]
#819 #

**Comment by EthanJWright** [comment]
Hey there,

Sorry about the belated response, some other things came up.

This solution looks like it works! I solved it a hacky way by pulling the crypto library in and building/moving it to the expected location.

Thanks for the quick response and update!
