### ISSUE TITLE
Registering delta after get_shadow call with persistent flag set to false, times-out

### ISSUE THREAD

**Issue by anubhutimittal1** [aws/aws-iot-device-sdk-embedded-C#816]
Steps to reproduce:

1. Call aws_iot_shadow_get() with isPersistentSubscribe = false
2. Call aws_iot_shadow_register_delta() which times-out after 20 seconds (commandTimeout) returning MQTT_REQUEST_TIMEOUT_ERROR
3. Subscribing to delta again, succeeds

Observation:
Setting isPersistentSubscribe = false somehow makes server send a publish message to topic aws/shadow/things/<thing_name>/get/accepted when aws_iot_shadow_register_delta is waiting for SUBACK during aws_iot_mqtt_internal_wait_for_read leading to a timeout.

This does not happen if isPersistentSubscribe is set to true for aws_iot_shadow_get() call.

**Comment by leegeth** [comment]
@anubhutimittal1 ,
Thanks for bringing this issue to our attention. I have a few follow up questions to understand the application code flow and help you better.

1. About call aws_iot_shadow_get() with isPersistentSubscribe = true and subsequent call to aws_iot_shadow_register_delta(). Was this the first time ever calling aws_iot_shadow_get() in the logic?
2. Would it be possible for you to share the code/code snippet with this sequence so that we can try to replicate the issue?

**Comment by leegeth** [comment]
@anubhutimittal1 ,

Thanks for getting all the required details. I am pasting the relevant part of the conversation here for helping others who would face similar issue in the future.
1.  if isPeristentSubscribe = true, it is always success. With isPersistentSubscribe = false, delta succeeds the second time.

As understood from the conversation, one possibility is that the call aws_iot_mqtt_internal_wait_for_read is not getting the right packet type. In order to confirm that, can you please try calling aws_iot_shadow_yield() a few times between the calls aws_iot_shadow_get() and aws_iot_shadow_register_delta()?

**Comment by abhidixi11** [comment]
Hey Anubhuti,  I'm assuming your question was answered and I'm closing this issue. If you have any further questions, please feel free to re-open or reach out to us.
Thanks!
