### ISSUE TITLE
Hardcoded MQTT keep-alive (10 minutes)

### ISSUE THREAD

**Issue by lerebel103** [aws/aws-iot-device-sdk-embedded-C#820]
Hi folks,

Are there any plans to expose the MQTT keep-alive period such that it can be configured at compile time or when initiating a connection. In both non-Shadow and Shadow backed clients this is hardcoded respectively to [60s](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/1c027cf3e9cd398c7486f1befd86b3e02d6aeaf2/include/aws_iot_mqtt_client.h#L147) and [600s](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/1c027cf3e9cd398c7486f1befd86b3e02d6aeaf2/src/aws_iot_shadow.c#L120) with `// NOTE: Temporary fix`.

I am working on a couple of projects requiring a finer control of MQTT keep-alive and ended forking Espressif's ESP32 port for [esp-aws-iot](https://github.com/lerebel103/esp-aws-iot) and [aws-iot-device-sdk-embedded-C](https://github.com/lerebel103/aws-iot-device-sdk-embedded-C/tree/e7056dcb0862797f77c00e4c65a0f3ad08cc3217) to get the desired effect as [this commit](https://github.com/lerebel103/aws-iot-device-sdk-embedded-C/commit/e7056dcb0862797f77c00e4c65a0f3ad08cc3217). However I am wondering what your plans were to address this longer term?

Cheers,
Will.

**Comment by dnoal** [comment]
Thank you for your inquiry.  We understand your request for user level configuration of MQTT keep-alive timeouts.  At this point, we are not making enhancements to V3 of our AWS IoT Embedded C SDK which currently is integrated with the ESP-IDF.  Our current work is focused on the V4_Beta branch and we will consider your feature request there.  V3 of the Embedded C SDK continues to be supported but we are focused on V4_Beta for innovation and new feature requests.  We are working with Espressif to get this newer version integrated in a similar fashion to offer choice to customers.

**Comment by lerebel103** [comment]
Thanks Dan,
Much appreciated, looking forward to it.
Cheers,
Will.

**Comment by aggarg** [comment]
@lerebel103 As Dan has already pointed out, we are not currently making enhancements to our v3 SDK. I still wanted to point out that you can configure keep alive interval for shadow by establishing the MQTT connection yourself and afterwards use the connected client for shadow operations.

In other words, instead of calling aws_iot_shadow_connect(), do what this function does in your application: https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_shadow.c#L106

Since you will call aws_iot_mqtt_connect, you will get a chance to specify the keep alive interval. The connected client (i.e. AWS_IoT_Client *) can then be used with the shadow APIs normally. I understand that it is not ideal but it will serve your purpose.

Hope that helps.

Thanks.

**Comment by lerebel103** [comment]
Thanks @aggarg thats not a bad workaround, true. 
Will.
