### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by penguin007-1** [aws/aws-iot-device-sdk-embedded-C#85]
Hi, 
I've downloaded the embedded SDK to my raspberry pi model A. Error occured while compiling the subscribe_publish_sample example:

**make -C ../../../external_libs/mbedTLS
make[1]: Entering directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS'
Makefile:63: recipe for target 'all' failed
make: *** [all] Error 2**

I'm sure that the private key, certificate and rootCA are placed in the certs directory. The aws_iot_config.h is modified correctly.

I think perhaps something is wrong with the Makefile settings. The SDK version is **2.1.1** according to CHANGELOG.md. 

I've got another raspberry Pi mode B, which has an earlier version **1.1.2** SDK. But there is no problem during compilation. 

Has anyone experienced the same problem? Could anyone provide suggestions? Thanks.

Jichun

**Comment by hedeshianaws** [comment]
Hello Jichun,

Version 2.1.1 has major changes from 1.1.2, so the build is a little different. This error message looks like you are missing the source files for mbedtls. Did you download the mbedtls source into your workspace? https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/external_libs/mbedTLS/README.txt
Unfortunately, it seems the instructions are a little unclear that this is something you explicitly need to do.

Please do let us know if this works for you, or if you have any other questions.

Harout

**Comment by penguin007-1** [comment]
Thanks very much Harout,

no, I didn't download it. 

Now the compilation can be executed. Though finally the binary file is generated, the compilation took horribly more than 10 minutes, it seems a lot of other files are compiled as well. Please see the following:

 $ sudo make
make -C ../../../external_libs/mbedTLS
make[1]: Entering directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS'
make[2]: Entering directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS/library'
  CC    aes.c
  CC    aesni.c
  CC    arc4.c
  CC    asn1parse.c
  CC    asn1write.c
  CC    base64.c
  CC    bignum.c
  CC    blowfish.c
  CC    camellia.c
  CC    ccm.c
  CC    cipher.c
  CC    cipher_wrap.c
  CC    ctr_drbg.c
  CC    des.c
  CC    dhm.c
  CC    ecdh.c
  CC    ecdsa.c
  CC    ecp.c
  CC    ecp_curves.c
  CC    entropy.c
  CC    entropy_poll.c
  CC    error.c
  CC    gcm.c
  CC    havege.c
  CC    hmac_drbg.c
  CC    md.c
  CC    md2.c
  CC    md4.c
  CC    md5.c
  CC    md_wrap.c
  CC    memory_buffer_alloc.c
  CC    oid.c
  CC    padlock.c
  CC    pem.c
  CC    pk.c
  CC    pk_wrap.c
  CC    pkcs12.c
  CC    pkcs5.c
  CC    pkparse.c
  CC    pkwrite.c
  CC    platform.c
  CC    ripemd160.c
  CC    rsa.c
  CC    sha1.c
  CC    sha256.c
  CC    sha512.c
  CC    threading.c
  CC    timing.c
  CC    version.c
  CC    version_features.c
  CC    xtea.c
  AR    libmbedcrypto.a
  RL    libmbedcrypto.a
  CC    certs.c
  CC    pkcs11.c
  CC    x509.c
  CC    x509_create.c
  CC    x509_crl.c
  CC    x509_crt.c
  CC    x509_csr.c
  CC    x509write_crt.c
  CC    x509write_csr.c
  AR    libmbedx509.a
  RL    libmbedx509.a
  CC    debug.c
  CC    net.c
  CC    ssl_cache.c
  CC    ssl_ciphersuites.c
  CC    ssl_cli.c
  CC    ssl_cookie.c
  CC    ssl_srv.c
  CC    ssl_ticket.c
  CC    ssl_tls.c
  AR    libmbedtls.a
  RL    libmbedtls.a
make[2]: Leaving directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS/library'
make[2]: Entering directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS/programs'
  CC    aes/aescrypt2.c
  CC    aes/crypt_and_hash.c
  CC    hash/hello.c
  CC    hash/generic_sum.c
  CC    pkey/dh_client.c
  CC    pkey/dh_genprime.c
  CC    pkey/dh_server.c
  CC    pkey/ecdsa.c
  CC    pkey/gen_key.c
  CC    pkey/key_app.c
  CC    pkey/key_app_writer.c
  CC    pkey/mpi_demo.c
  CC    pkey/pk_decrypt.c
  CC    pkey/pk_encrypt.c
  CC    pkey/pk_sign.c
  CC    pkey/pk_verify.c
  CC    pkey/rsa_genkey.c
  CC    pkey/rsa_decrypt.c
  CC    pkey/rsa_encrypt.c
  CC    pkey/rsa_sign.c
  CC    pkey/rsa_verify.c
  CC    pkey/rsa_sign_pss.c
  CC    pkey/rsa_verify_pss.c
  CC    ssl/dtls_client.c
  CC    ssl/dtls_server.c
  CC    ssl/ssl_client1.c
  CC    ssl/ssl_client2.c
  CC    ssl/ssl_server.c
  CC    ssl/ssl_server2.c
  CC    ssl/ssl_fork_server.c
  CC    ssl/mini_client.c
  CC    ssl/ssl_mail_client.c
  CC    random/gen_entropy.c
  CC    random/gen_random_havege.c
  CC    random/gen_random_ctr_drbg.c
  CC    test/ssl_cert_test.c
  CC    test/benchmark.c
  CC    test/selftest.c
  CC    test/udp_proxy.c
  CC    util/pem2der.c
  CC    util/strerror.c
  CC    x509/cert_app.c
  CC    x509/crl_app.c
  CC    x509/cert_req.c
  CC    x509/cert_write.c
  CC    x509/req_app.c
make[2]: Leaving directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS/programs'
make[2]: Entering directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS/tests'
  Gen   test_suite_aes.ecb.c
  CC    test_suite_aes.ecb.c
  Gen   test_suite_aes.cbc.c
  CC    test_suite_aes.cbc.c
  Gen   test_suite_aes.cfb.c
  CC    test_suite_aes.cfb.c
  Gen   test_suite_aes.rest.c
  CC    test_suite_aes.rest.c
  Gen   test_suite_arc4.c
  CC    test_suite_arc4.c
  Gen   test_suite_asn1write.c
  CC    test_suite_asn1write.c
  Gen   test_suite_base64.c
  CC    test_suite_base64.c
  Gen   test_suite_blowfish.c
  CC    test_suite_blowfish.c
  Gen   test_suite_camellia.c
  CC    test_suite_camellia.c
  Gen   test_suite_ccm.c
  CC    test_suite_ccm.c
  Gen   test_suite_cipher.aes.c
  CC    test_suite_cipher.aes.c
  Gen   test_suite_cipher.arc4.c
  CC    test_suite_cipher.arc4.c
  Gen   test_suite_cipher.ccm.c
  CC    test_suite_cipher.ccm.c
  Gen   test_suite_cipher.gcm.c
  CC    test_suite_cipher.gcm.c
  Gen   test_suite_cipher.blowfish.c
  CC    test_suite_cipher.blowfish.c
  Gen   test_suite_cipher.camellia.c
  CC    test_suite_cipher.camellia.c
  Gen   test_suite_cipher.des.c
  CC    test_suite_cipher.des.c
  Gen   test_suite_cipher.null.c
  CC    test_suite_cipher.null.c
  Gen   test_suite_cipher.padding.c
  CC    test_suite_cipher.padding.c
  Gen   test_suite_ctr_drbg.c
  CC    test_suite_ctr_drbg.c
  Gen   test_suite_debug.c
  CC    test_suite_debug.c
  Gen   test_suite_des.c
  CC    test_suite_des.c
  Gen   test_suite_dhm.c
  CC    test_suite_dhm.c
  Gen   test_suite_ecdh.c
  CC    test_suite_ecdh.c
  Gen   test_suite_ecdsa.c
  CC    test_suite_ecdsa.c
  Gen   test_suite_ecp.c
  CC    test_suite_ecp.c
  Gen   test_suite_error.c
  CC    test_suite_error.c
  Gen   test_suite_entropy.c
  CC    test_suite_entropy.c
  Gen   test_suite_gcm.aes128_de.c
  CC    test_suite_gcm.aes128_de.c
  Gen   test_suite_gcm.aes192_de.c
  CC    test_suite_gcm.aes192_de.c
  Gen   test_suite_gcm.aes256_de.c
  CC    test_suite_gcm.aes256_de.c
  Gen   test_suite_gcm.aes128_en.c
  CC    test_suite_gcm.aes128_en.c
  Gen   test_suite_gcm.aes192_en.c
  CC    test_suite_gcm.aes192_en.c
  Gen   test_suite_gcm.aes256_en.c
  CC    test_suite_gcm.aes256_en.c
  Gen   test_suite_gcm.camellia.c
  CC    test_suite_gcm.camellia.c
  Gen   test_suite_hmac_drbg.misc.c
  CC    test_suite_hmac_drbg.misc.c
  Gen   test_suite_hmac_drbg.no_reseed.c              
  CC    test_suite_hmac_drbg.no_reseed.c                       
  Gen   test_suite_hmac_drbg.nopr.c
  CC    test_suite_hmac_drbg.nopr.c
  Gen   test_suite_hmac_drbg.pr.c
  CC    test_suite_hmac_drbg.pr.c
  Gen   test_suite_md.c
  CC    test_suite_md.c
  Gen   test_suite_mdx.c
  CC    test_suite_mdx.c
  Gen   test_suite_memory_buffer_alloc.c
  CC    test_suite_memory_buffer_alloc.c
  Gen   test_suite_mpi.c
  CC    test_suite_mpi.c
  Gen   test_suite_pem.c
  CC    test_suite_pem.c
  Gen   test_suite_pkcs1_v21.c
  CC    test_suite_pkcs1_v21.c
  Gen   test_suite_pkcs5.c
  CC    test_suite_pkcs5.c
  Gen   test_suite_pkparse.c
  CC    test_suite_pkparse.c
  Gen   test_suite_pkwrite.c
  CC    test_suite_pkwrite.c
  Gen   test_suite_pk.c
  CC    test_suite_pk.c
  Gen   test_suite_rsa.c
  CC    test_suite_rsa.c
  Gen   test_suite_shax.c
  CC    test_suite_shax.c
  Gen   test_suite_ssl.c
  CC    test_suite_ssl.c
  Gen   test_suite_x509parse.c
  CC    test_suite_x509parse.c
  Gen   test_suite_x509write.c
  CC    test_suite_x509write.c
  Gen   test_suite_xtea.c
  CC    test_suite_xtea.c
  Gen   test_suite_version.c
  CC    test_suite_version.c
make[2]: Leaving directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS/tests'
make[1]: Leaving directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS'

Fortunately the generated binary file can be executed. I don't understand why the compilation took so long. The compilation of the other lower version (1.1.2) took just less than one minute, only a few files are compiled. 

Jichun

**Comment by hedeshianaws** [comment]
Hello Jichun,

As you have discovered, the SDK sample programs naively build mbedtls with all cipher suites and optional configuration. Additionally, the mbedtls builds run unit tests on each build, thus making the builds take even longer. If the build time or binary size is an issue, you could modify the build for your particular application to not build any of the additional components or cipher suites you are not interested in.

We are looking to improve the build process with the next release in order to address some of these and other concerns.

Harout

**Comment by penguin007-1** [comment]
Hi Harout,

thanks a lot.

Jichun

**Comment by mehran1977** [comment]
Dear 
  I did all of them but i have error in making sample , so it cant find mbedtls/library/libmbedcrypto.a: No such file or directory
how i can solve that ?
thanks
Mehran

**Comment by Lakshana3** [comment]
> gcc: error: ../../../external_libs/mbedTLS/library/libmbedcrypto.a: No such file or directory
> Makefile:63: recipe for target 'all' failed
> make: *** [all] Error 1

I'm facing the same issue. Please help.
Thanks.

**Comment by deeplyembeddedWP** [comment]
To get rid of that issue, ensure you have copied the lasted mbedTLS from the official website. Using the development branch caused me the same issue.

**Comment by 15926273249** [comment]
Hello JiChun, 
  CC    test_suite_pkcs1_v15.c
make[2]: Leaving directory '/opt/nvidia/deepstream/deepstream-5.0/sources/libs/aws_protocol_adaptor/aws-iot-sdk/external_libs/mbedTLS/mbedtls/tests'
make[2]: Entering directory '/opt/nvidia/deepstream/deepstream-5.0/sources/libs/aws_protocol_adaptor/aws-iot-sdk/external_libs/mbedTLS/mbedtls'
make[2]: Leaving directory '/opt/nvidia/deepstream/deepstream-5.0/sources/libs/aws_protocol_adaptor/aws-iot-sdk/external_libs/mbedTLS/mbedtls'
make[1]: Leaving directory '/opt/nvidia/deepstream/deepstream-5.0/sources/libs/aws_protocol_adaptor/aws-iot-sdk/external_libs/mbedTLS/mbedtls'
gcc: warning: ../aws-iot-sdk/external_libs/mbedTLS/mbedtls/library/libmbedtls.a: linker input file unused because linking not done
gcc: warning: ../aws-iot-sdk/external_libs/mbedTLS/mbedtls/library/libmbedcrypto.a: linker input file unused because linking not done
gcc: warning: ../aws-iot-sdk/external_libs/mbedTLS/mbedtls/library/libmbedx509.a: linker input file unused because linking not done
/usr/bin/ld: ../aws-iot-sdk/external_libs/mbedTLS/mbedtls/library/x509_crt.o: relocation R_X86_64_PC32 against symbol `mbedtls_x509_parse_subject_alt_name' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:105: recipe for target 'all' failed
make: *** [all] Error 1

How can I solve this problem?

**Comment by AnamikaPaul** [comment]
I am having same issue ,please help

make[2]: Leaving directory '/opt/nvidia/deepstream/deepstream-6.0/sources/libs/aws_protocol_adaptor/aws-iot-sdk/external_libs/mbedTLS/mbedtls/tests'
make[2]: Entering directory '/opt/nvidia/deepstream/deepstream-6.0/sources/libs/aws_protocol_adaptor/aws-iot-sdk/external_libs/mbedTLS/mbedtls'
make[2]: Leaving directory '/opt/nvidia/deepstream/deepstream-6.0/sources/libs/aws_protocol_adaptor/aws-iot-sdk/external_libs/mbedTLS/mbedtls'
make[1]: Leaving directory '/opt/nvidia/deepstream/deepstream-6.0/sources/libs/aws_protocol_adaptor/aws-iot-sdk/external_libs/mbedTLS/mbedtls'
**gcc: warning: ../aws-iot-sdk/external_libs/mbedTLS/mbedtls/library/libmbedtls.a: linker input file unused because linking not done
gcc: warning: ../aws-iot-sdk/external_libs/mbedTLS/mbedtls/library/libmbedcrypto.a: linker input file unused because linking not done
gcc: warning: ../aws-iot-sdk/external_libs/mbedTLS/mbedtls/library/libmbedx509.a: linker input file unused because linking not done**
