### ISSUE TITLE
device missed delta event when auto-reconnecting.

### ISSUE THREAD

**Issue by bennettChen** [aws/aws-iot-device-sdk-embedded-C#87]
this issue is similar as https://github.com/aws/aws-iot-device-sdk-js/issues/100
just it is in embedded C version. 

my embedded device always miss coming delta event during auto-reconnecting period.
in Node.js version, it may be resolved (a workaround) by getting whole shadow document.
and in embedded-C version, any idea for this?

thanks for any comment and help.

**Comment by bennettChen** [comment]
refer to http://aws-iot-device-sdk-embedded-c-docs.s3-website-us-east-1.amazonaws.com/aws__iot__shadow__interface_8h.html#a8d5bac9f2b56664cb600139635aca383

we have this function.
IoT_Error_t aws_iot_shadow_get 	( 	AWS_IoT_Client *  	pClient,
		const char *  	pThingName,
		fpActionCallback_t  	callback,
		void *  	pContextData,
		uint8_t  	timeout_seconds,
		bool  	isPersistentSubscribe 
	) 	


this can be a work around solution to get all shadow document.
but its not the correct solution.

**Comment by gustavomassa** [comment]
Every time that the device boot/restart, I call "aws_iot_shadow_get" to get the last updated data from the cloud and sync with the firmware. I think actually it is the only solution available.

**Comment by hedeshianaws** [comment]
Thank you for you response  @gustavomassa 

Hello @bennettChen, Thank you for your interest in AWS IoT. As suggested by @gustavomassa and explained by @fengsongAWS in the js SDK, the device will not receive shadow updates when it is disconnected. Since the last update is the most current update, calling shadow_get and reading the delta portion of the shadow should get what you need.

Please let us know if you have any additional questions.

**Comment by Borschtsch** [comment]
Hi @bennettChen. Another way to get the delta is to send your copy of parameter values to the server and it will trigger the delta for you if it sees any difference.

**Comment by chaurah** [comment]
Please reopen if you are still facing issues.
