### ISSUE TITLE
Question: Is there a planned release and what is the level of support?

### ISSUE THREAD

**Issue by bpair** [aws/aws-iot-device-sdk-embedded-C#89]
We are using AWS IoT for  our new product and have been planning to use the AWS IoT embedded client, but before we use this library versus paying for a commercial MQTT client that supports TLS and can run in FreeRTOS, we would like to know a little more about how well this library is maintained.

I see a lot of activity on the JS iot client but not much on the embedded c client. Is AWS supporting this? If we pay for support with AWS do we get support for this? 

Is there a planned release schedule? There are some significant looking bugs raised around 6 months ago that have not been addressed yet.

I am not being critical, just looking for some information before we choose this library.

thanks.

**Comment by hedeshianaws** [comment]
Thank you for your interest in the AWS IoT Embedded-C SDK. Are you looking for just MQTT functionality? Or are you also interested in AWS IoT device shadow support as well? If you are just looking for MQTT, I would recommend using a 3rd party dedicated library for microcontrollers instead of using the AWS IoT C SDK. We are working on updates to the SDK that would make it more appropriate to your application and fix some long standing architectural issues which make this SDK difficult if not impossible to use on FreeRTOS class devices. However, I cannot comment on when that version will be available.

This SDK is an official SDK supported by AWS, however, it doesn’t work out of the box on MCU class of devices which is why using something else that works better for microcontrollers is recommended for your use case. I understand your skepticism about existing IoT C SDK, and I don't think it is misplaced.

**Comment by kaidokert** [comment]
Would be interesting to hear which 3rd party MQTT libraries are validated and tested against AWS IoT, that are suitable for RTOS-class devices.

**Comment by bpair** [comment]
This has been a big disappointment for us. It looks as though we will end up using wolfSSL/wolfMQTT. It does work, but still requires some integration work. The downside is, it costs $5000 for a license. That basically goes against how Amazon has setup their services; "Free to get started, pay only for what you need".
TLS over MQTT with auto-reconnect is just difficult on RTOS. We would love to be using this library instead of wolfSSL but our project deadline makes that impossible. For $5k you can purchase a ton of Pi Zero W boards or even Beagle Bone Black Wireless boards and avoid these issues. If your volumes are small the extra money on boards offsets the extra development and firmware costs.

**Comment by drodgers-ls** [comment]
I'm also disappointed to read the (presumably official) AWS comments.  It seems that Amazon's definition of "embedded" is rather generous, in that a Linux-capable platform is assumed.  I'm developing for a Cortex-M4 platform with 1MB flash and 256KB SRAM running FreeRTOS, and being told that this library is "difficult if not impossible to use" is, at the very least, a red flag not to use this library.  It shouldn't be necessary for a network-capable device to require a separate higher-end device to serve as an MQTT gateway.

I also doubt AWS' commitment to this particular solution, as it has been a year since the last release, despite multiple responses over the last year promising various features and fixes for the next release.

I too will be investigating other embedded MQTT solutions (most likely wolfMQTT).  I would make a strong recommendation... since AWS is aware that this embedded solution suffers from architectural issues, and isn't scalable to microcontrollers, then perhaps there's an opportunity to re-architect this software solution properly.  I would like to see AWS provide separate C (or C++) SDKs for AWS IoT **device objects**, and AWS IoT **network communications**, or at the least, provide a layer of separation between the two.  I don't know if wolfMQTT provides implementation for Things or Thing Shadows, but it would be nice to attach an AWS-provided Thing library to my wolfMQTT communication component.

**Comment by Borschtsch** [comment]
I joined too late to this thread.

Based on my experience I can tell that library fits well into small devices, like in my STM32L4 with 512K Flash and 128K RAM. MCU runs FreeRTOS, 15 different tasks and only two of them are actually servicing AWS IoT. I still have 10K RAM for spare!

Yes, the SDK cannot work on MCU out of the box, but I warn users that you should know exactly what you are doing with AWS IoT SDK. It is easy get on board, but take efforts to master your skills. 

Here are my thoughts if anyone is interested.
If one plans to work with AWS IoT service then he should not spend time looking for other MQTT options. SDK MQTT implementation is well tested, you get support for it and it is good enough for MCU, just look at the memory map listing (I just looked, 8K Flash, **no static RAM allocation**).

The TLS part is left out of the SDK responsibility - it is up to the user to choose TLS/SSL implementation. We overcomed this issue by using GSM modem with SSL support which was a big help. The SDK provides some reference implementation based on mbedTLS, but you have to make sure you have configured it right to minimize TLS/SSL memory footprint.

The real problem with the SDK is the implementation of the Thing Shadow. You cannot not see the problem until you have tons of parameters in the Shadow.
I had to refactor Shadow related parts of the SDK to avoid **huge** RAM overhead for Device Thing Shadow with about 800 JSON tokens because of the JSON parser selected for this SDK - this part the SDK can't play well and I pinpointed issues with their JSON parser about a year ago. Their JSON parser builds full JSON metadata tree (14K RAM in my case!) before SDK can access Shadow data. But it is important to realize that SDK can access the JSON file directly without man in the middle - the JSON parser could be turned into a one-pass static JSON tree traversal instead.

A hint to users: consider not subscribing to 'accepted' topic if you intentionnaly not planning on using it to drive some internal logic. 'accepted messages contain a lot of metadata and in most cases the size of the 'accepted' message is much bigger than size of 'delta'. This will allow you to tune down the MQTT/Shadow RAM buffers.
Sometimes my 'accepted' was about 16K in size because of this metadata, however the maximum 'delta' size according to AWS IoT documentation shall be around 4K (8K for both desired/reported sections).

A hint to the SDK developers: you really need to get embedded expertise to work on the Shadow part. I do not know your plans on new SDK, but users should not pay extra RAM for each parameter defined in the Shadow.

Regards,
-Dmitry

**Comment by chrismrutherford** [comment]
Adding to comments from @Borschtsch .  I have shadow working with mbedTLS over a GPRS modem which unfortunately does not support SSL.  The platform is an STM32F7 1MB Flash, 320K RAM.  The TLS library takes quite a big chunk out of the RAM and ROM, not leaving much for Shadow RAM buffers.  If amazon intends to target STM32x FreeRTOS based platforms then making the Shadow more efficient is a must.  I'm even considering writing my own wrapper for the mqtt interface.

The STM32F7 is a high spec embedded micro controller and I'm already concerned about RAM / ROM constraints, lower spec micros for use in mass produced items such as light bulbs/switches etc are going to struggle to get this SDK running.  Requiring a Linux based platform significantly increases the BOM cost, and is overkill for many applications.

**Comment by chrismrutherford** [comment]
@Borschtsch re "A hint to users: consider not subscribing to 'accepted' topic if you intentionnaly not planning on using it to drive some internal logic".  

Did you modify the source to do this, or write your own?  I seem to end up with a memory leak if I do this using the shadow SDK.  Presumably from the unacknowledged updates.  It seems the embedded C client gets 'accepted' messages, even when another client updates the shadow.

**Comment by gordonwang0** [comment]
Hello everyone,

Sorry for the late reply, but I have some updates to share on this.

As you may have noticed, the team I'm on (which also supports Amazon FreeRTOS) took ownership of this SDK in February this year.  Since then, we've been working to improve this library and combine it with the libraries shipped with Amazon FreeRTOS.

The end result of this has been the release of version 4 beta, which is currently available on [this branch](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/v4_beta).  Please give it a try if you have time.  Note that as a beta version, it may have bugs or performance issues.

We will continue to fix bugs in v3.0.1 even after v4 is released, but may not add any new features to v3.
We have also sought to remedy the resource usage issues in v4.  Note that we are not finished with this part yet.

Please let me know if you have any further questions.
