### ISSUE TITLE
AWS IoT Shadow delta JSON version number does not increment 

### ISSUE THREAD

**Issue by ravigainspan** [aws/aws-iot-device-sdk-embedded-C#90]
I have downloaded the "AWS IoT Device SDK" for Embedded C source code. I built it and ran the executable binary on our Native Development Starter Kit to securely connect to the AWS IoT platform.The Device is connected to AWS IoT successfully. I tried to control the Device LED State from AWS IoT MQTT Client by using JSON Object.
{ "state": { "desired" : {"LED" : 1 } } }

The device received the desired state on the "shadow/update/delta" topic.But mostly I received the following error message.
"Old Delta Message received - Ignoring rx: 73427 local: 73427"
Which results in a delay in delta notification. 
I found that the bug is caused by receiving two separate messages "update /accept and update/delta" with the same version number.

Could you send your suggestion/feedback on this concern? Because we are going to get AWS certificate Once this concern is addressed as soon as possible.

I think the solution is either AWS IoT server shall increment the shadowJsonVersionNum for update/delta, Or SDK shall use the separate version number for shadow/update/delta.

**Comment by vareddy** [comment]
Hi @ravigainspan ,
Thank you for your interest in AWS IoT!
This is expected behavior if you subscribe to both the update/accept and the update/delta topics. This block [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_shadow_records.c#L498) defines the behavior. 
A couple of changes you can try for your use case are:
1. Change the more than (>) to more than or equal to (>=) on [this line](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_shadow_records.c#L500) OR
2. set the shadowDiscardOldDeltaFlag to false [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_shadow_records.c#L83)

Please let us know if these changes work or if you have any more questions about the SDK. 
Thanks!
Varun

**Comment by ravigainspan** [comment]
this fix is working fine. thanks for the response
