### ISSUE TITLE
MQTT_REQUEST_TIMEOUT_ERROR(-28) during aws_iot_mqtt_publish() 

### ISSUE THREAD

**Issue by ashokgaddam** [aws/aws-iot-device-sdk-embedded-C#946]
Hi,
Occasionally, I have been observing that return value as MQTT_REQUEST_TIMEOUT_ERROR(-28) when my IOT device tries to publish the data with Qos1 to the AWS server.
Even though we received MQTT_REQUEST_TIMEOUT_ERROR, we observed that data is successfully published to AWS server.

Here are my questions
1. Can we always consider MQTT_REQUEST_TIMEOUT_ERROR(-28) as success in application ?
2. Is there a scenario we get this error (-28) when connection between client and Host server is lost ?
3. Is it good idea to retry the publish again whenever we see the return value as MQTT_REQUEST_TIMEOUT_ERROR(-28) to ensure publish data reached successfully to the cloud?

mqttInitParams.mqttCommandTimeout_ms = 20000;
AWS C SDK version - 3.0.1

~Ashok

**Comment by abhidixi11** [comment]
Hello Ashok,
Thanks for reaching out. 
MQTT_REQUEST_TIMEOUT_ERROR is general timeout error code returned when any receive call times out when the library is expecting to receive something.  In your case it is PUBACK, the client has sent publish and library times out waiting for PUBACK.

Since MQTT uses TCP, it guaranteed by the TCP that the Publish will be delivered, unless the connection goes down due to various reasons.  Therefore you are seeing that your data is successfully published even though you see the error. 
You can ignore the error for the publish call, but may want to use it to track it QOS1 packet was delivered or not. You may want to publish the packet again ( as you have pointed out in #3) .  Since QOS1 is at least once delivery, it is OK to send same publish (with same packetId). But usually it should be resent only if the connection goes down.

So to answer your questions:
1.  MQTT_REQUEST_TIMEOUT_ERROR is a timeout and various calls may have different interpretation.  For Publish, it is telling the application that it could not receive PUBACK, So for the publish call you can treat is as success ( or rather not a failure ), but for subscribe, you may want send subscribe again. 
2. No. You may get this error and followed by more severe error for subsequent API call, if connection has indeed gone down. But this error alone does not indicate that the connection is lost.
3. As discussed above, you may want to send Publish again after you receive this error for publish API. 
Please let us know if you have any more questions.
Thanks.

**Comment by ashokgaddam** [comment]
Thanks for your response.

On point 2, I agree we will not be knowing the connection status (connected or lost) based on the timeout error. But, is it possible to determine the connection status is active or not by calling aws_iot_mqtt_is_client_connected(&mqttClient) when MQTT_REQUEST_TIMEOUT_ERROR happens.

Here is snippet of code

![image](https://user-images.githubusercontent.com/64396938/82407175-211c0100-9a86-11ea-9ec6-f4de9ccd6bcd.png)


~Ashok

**Comment by abhidixi11** [comment]
Hello Ashok,
aws_iot_mqtt_publish() checks for the client state before sending publish, so it will not send publish if client state was 'disconnected'.  Also this function does not change the client state to disconnected; therefore; the code above will always return false. 
If the error is something other than than timeout (eg, NETWORK_SSL_READ_ERROR, NETWORK_SSL_WRITE_ERROR) , then mostl likely the connection is down. and the application should close MQTT session and reconnect. ( aws_io_mqtt_is_client_connected() may not tell you that). 
Disconnect will be detected by yield function. If your application periodically runs yield , it will set the state to disconnect when ping fails and trigger reconnect logic.  Hope this helps. 
Thanks,
Abhijit

**Comment by ashokgaddam** [comment]
Thanks again Abhijit for the response. 

Another question regarding aws_iot_shadow_yield(), some times i see return code as FAILURE.  Is FAILURE is considered as network disconnection or it is a general failure in the AWS library?  Currently, we are doing a retry once   awsIotShadowYield() in case of Failure and also checking aws_iot_mqtt_is_client_connected() to know network status.  I wanted to understand is this error is really network disconnect or not and how to handle the failure error code 

Code Snippet for Failure rc:

IoT_Error_t rc = aws_iot_shadow_yield(&mqttClient, timeOut);
if (rc == FAILURE)
{ 
     bool isconnected = aws_iot_mqtt_is_client_connected(&mqttClient);
     if (isconnected)
     {
          // Connection active
     }
    else
    {
           //Connection lost
    }
} 

~Ashok

**Comment by abhidixi11** [comment]
Hello Ashok,
aws_iot_shadow_yield basically calls aws_iot_mqtt_yield().
Here is doxygen comment for aws_iot_mqtt_yield()
```
* @return `IoT_Error_t`: See `aws_iot_error.h`
* @return If this call results a negative value, assume the MQTT connection has dropped.
* @ref mqtt_function_is_client_connected can be called to confirm. If a reconnection is
* needed, @ref mqtt_function_attempt_reconnect should be called.
```
So the code snippet above should work correctly.
Thanks,
Abhijit

**Comment by ashokgaddam** [comment]
Thank you!. Closing this issue.
